import 'package:flutter/material.dart';

class LocaleNotifier extends ChangeNotifier {
  String _locale = AppLocale.currentLocale;
  String get locale => _locale;

  void change(String locale) {
    _locale = locale;
    AppLocale.currentLocale = locale;
    notifyListeners();
  }
}

class AppLocale {
  static String currentLocale = 'tr';

  static bool get isEnglish => currentLocale == 'en';
  static bool get isTurkish => currentLocale == 'tr';
  static bool get isGerman => currentLocale == 'de';

  static void change(String locale) {
    currentLocale = locale;
  }

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'home': 'Home',
      'library': 'Library',
      'search': 'Search',
      'settings': 'Settings',
      'now_playing': 'Now Playing',
      'no_song_playing': 'No song playing',
      'no_music_playing': 'No music playing',
      'your_music_awaits': 'Your music awaits',
      'import_songs_to_start': 'Import songs from your device to get started',
      'import_music': 'Import Music',
      'liked_songs': 'Liked Songs',
      'albums': 'Albums',
      'popular_artists': 'Popular Artists',
      'playlists': 'Playlists',
      'see_all': 'See All',
      'your_top_mixes': 'Your Top Mixes',
      'recently_added': 'Recently Added',
      'songs': 'Songs',
      'artists': 'Artists',
      'genres': 'Genres',
      'sort_by_title': 'Sort by Title',
      'sort_by_artist': 'Sort by Artist',
      'sort_by_album': 'Sort by Album',
      'sort_by_duration': 'Sort by Duration',
      'sort_by_date_added': 'Sort by Date Added',
      'no_albums_found': 'No albums found',
      'no_artists_found': 'No artists found',
      'no_genres_found': 'No genres found',
      'your_library_is_empty': 'Your library is empty',
      'import_music_from_device': 'Import music from your device',
      'scan_music_library': 'Scan Music Library',
      'what_to_listen': 'What do you want to listen to?',
      'recent_searches': 'Recent Searches',
      'clear': 'Clear',
      'browse_all': 'Browse All',
      'no_results_for': 'No results for',
      'queue': 'Queue',
      'queue_is_empty': 'Queue is empty',
      'add_songs': 'Add Songs',
      'all_songs_added': 'All songs already added',
      'add_songs_to_start': 'Add songs to start playing',
      'add_to_playlist': 'Add to Playlist',
      'song_info': 'Song Info',
      'share': 'Share',
      'sleep_timer': 'Sleep Timer',
      'no_playlists_yet': 'No playlists yet. Create one first.',
      'create_new_playlist': 'Create New Playlist',
      'new_playlist': 'New Playlist',
      'playlist_name': 'Playlist name',
      'cancel': 'Cancel',
      'close': 'Close',
      'rename_playlist': 'Rename Playlist',
      'delete_playlist': 'Delete Playlist',
      'rename': 'Rename',
      'delete': 'Delete',
      'delete_playlist_warning': 'Are you sure you want to delete',
      'no_songs_in_playlist': 'No songs in this playlist',
      'add_songs_from_library': 'Add songs from the library',
      'play': 'Play',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'theme_mode': 'Theme Mode',
      'custom_colors': 'Custom Colors',
      'dark': 'Dark',
      'light': 'Light',
      'system': 'System',
      'language': 'Language',
      'app_language': 'App Language',
      'music_library': 'Music Library',
      'rescan_library': 'Rescan Library',
      'scan_device_for_music': 'Scan device for new or removed music',
      'import_from_files': 'Import from Files',
      'browse_and_import': 'Browse and import audio files',
      'import_from_folder': 'Import from Folder',
      'scan_folder_for_music': 'Scan a specific folder for music',
      'storage': 'Storage',
      'local_songs': 'Local Songs',
      'songs_in_library': 'songs in library',
      'clear_library': 'Clear Library',
      'remove_cached_data': 'Remove all cached music data',
      'clear_library_title': 'Clear Library',
      'clear_library_confirm':
          'This will remove all cached music data. Your actual music files will not be deleted.',
      'audio': 'Audio',
      'equalizer': 'Equalizer',
      'adjust_sound_frequencies': 'Adjust sound frequencies',
      'equalizer_coming_soon': 'Equalizer coming soon',
      'equalizer_not_available': 'Equalizer not available on this device',
      'accounts': 'Accounts',
      'connected_as': 'Connected as',
      'disconnect': 'Disconnect',
      'spotify': 'Spotify',
      'connect_spotify_description':
          'Import your Spotify playlists and liked songs. Connect with your browser cookie.',
      'spotify_cookie_instructions':
          '1. Go to open.spotify.com in a browser\n2. Log in\n3. Open DevTools (F12) > Application > Cookies\n4. Copy the value of "sp_dc"\n5. Paste it below',
      'paste_sp_dc_cookie': 'Paste sp_dc cookie',
      'import_liked_songs': 'Import Liked Songs',
      'spotify_connected_as': 'Connected as',
      'enter_spotify_username': 'Spotify username (optional)',
      'connect_spotify': 'Connect Spotify library',
      'i_authorized': 'I Authorized',
      'auth_failed_try_again': 'Authorization failed. Please try again.',
      'presets': 'Presets',
      'default_playback_speed': 'Default Playback Speed',
      'volume_boost': 'Volume Boost',
      'playback': 'Playback',
      'auto_shuffle': 'Auto Shuffle',
      'automatically_shuffle': 'Automatically shuffle when playing',
      'gapless_playback': 'Gapless Playback',
      'seamless_transition': 'Seamless transition between songs',
      'crossfade': 'Crossfade',
      'seconds_crossfade': 's crossfade',
      'off': 'Off',
      'apply': 'Apply',
      'about': 'About',
      'version': 'Version',
      'built_with_flutter': 'Built with Flutter & Love',
      'acknowledgments': 'Acknowledgments',
      'credits': 'Credits',
      'open_source_licenses': 'Open source components & licenses',
      'developer': 'Developer',
      'repeat_all': 'Repeat All',
      'repeat_one': 'Repeat One',
      'shuffled': 'Shuffled',
      'added_to': 'Added to',
      'created_and_added_to': 'Created and added to',
      'no_songs': 'No songs',
      'english': 'English',
      'turkish': 'Turkish',
      'german': 'German',
      'scan_media_library': 'Scan Media Library',
      'import_from_apple_music': 'Import from Apple Music library',
      'browse_files': 'Browse Files',
      'select_audio_files': 'Select audio files from Files app',
      'import_from_folder_title': 'Import from Folder',
      'scan_specific_folder': 'Scan a specific folder',
      'seconds': 'seconds',
      'melodi': 'Melodi',
      'add_to_queue': 'Add to Queue',
      'play_next': 'Play Next',
      'view_album': 'View Album',
      'view_artist': 'View Artist',
      'watched_folder': 'Watched Folder',
      'auto_scan_folder': 'Auto-scan a folder on every launch',
      'watching': 'Watching',
      'folder_set': 'Folder set',
      'could_not_open_link': 'Could not open link',
      'youtube_search_hint': 'Search on YouTube',
      'downloading': 'Downloading...',
      'download_complete': 'Download complete',
      'download_failed': 'Download failed',
      'loading_song': 'Loading',
      'sleep_timer_canceled': 'Sleep timer canceled',
      'output_selection': 'Output selection coming soon',
      'device_selection': 'Device selection coming soon',
      'artist_label': 'Artist',
      'album_label': 'Album',
      'genre_label': 'Genre',
      'year_label': 'Year',
      'track_label': 'Track',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Duration',
      'file_label': 'File',
      'accent_color': 'Accent Color',
      'tap_to_change': 'Tap to change',
      'background': 'Background',
      'surface': 'Surface',
      'card': 'Card',
      'text_primary': 'Text Primary',
      'text_secondary': 'Text Secondary',
      'reset_colors': 'Reset Colors',
      'default_color': 'Default',
      'create_playlist': 'Create Playlist',
      'share_song': 'Share Song',
      'share_file': 'Share Audio File',
      'now_playing_queue': 'Playing from Queue',
      'song_count': 'songs',
      'min': 'min',
      'hr': 'hr',
      'dynamic_colors': 'Dynamic Colors',
      'apply_album_colors': 'Apply colors from album art',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description':
          'Import your YouTube Music library. Connect with your browser cookie.',
      'ytmusic_cookie_instructions':
          '1. Go to music.youtube.com in a browser\n2. Log in\n3. Open DevTools (F12) > Application > Cookies\n4. Copy the value of "__Secure-3PSAPISID"\n5. Paste it below',
      'paste_ytmusic_cookie': 'Paste SAPISID cookie',
      'import_albums': 'Import Albums',
      'connect_youtube_music': 'Connect YouTube Music',
      'auto_sync': 'Auto Sync',
      'sync_time': 'Sync Time',
      'wifi_only': 'Wi-Fi Only',
      'sync_schedule': 'Sync Schedule',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'stream_on_cellular': 'Stream on Cellular',
      'streaming': 'Streaming',
      'synced_lyrics': 'Synced Lyrics',
      'no_lyrics': 'No lyrics available',
      'instrumental': 'Instrumental',
      'login_with_browser': 'Login with Browser',
      'cookie_paste': 'or paste cookie manually',
      'like_mirroring': 'Like Mirroring',
      'mirror_likes': 'Mirror Likes',
      'mirroring_enabled': 'Mirroring enabled',
      'mirrored_count': 'Mirrored',
      'mirror_now': 'Mirror Now',
      'last_mirrored': 'Last mirrored',
      'mirror_likes_description':
          'Keep likes in sync between Spotify and YouTube Music',
      'mixes': 'Mixes',
      'release_radar': 'Release Radar',
      'discover_weekly': 'Discover Weekly',
      'regenerate': 'Regenerate',
      'no_mixes_yet': 'No mixes generated yet',
      'generated_at': 'Generated',
      'diagnostics': 'Diagnostics',
      'export_diagnostics': 'Export',
      'clear_logs': 'Clear Logs',
      'error_logs': 'Error Logs',
      'service_status': 'Service Status',
      'app_info': 'App Info',
      'crash_reports': 'Crash Reports',
      'scrobbling': 'Scrobbling',
      'yt_history_scrobbling': 'YouTube History Scrobbling',
      'scrobble_now': 'Scrobble Now',
      'scrobbled_count': 'Scrobbled',
      'scrobbling_enabled': 'Auto-scrobble',
      'last_scrobbled': 'Last scrobbled',
      'recent_scrobbles': 'Recent',
      'auth_expired': 'Connection Expired',
      'reconnect': 'Reconnect',
      'auth_expired_desc':
          'Your {service} connection has expired. Tap to reconnect.',
      'streaming_prompt_title': 'Streaming Mode',
      'streaming_prompt_body': 'This track needs download. Stream instead?',
      'stream': 'Stream',
      'download': 'Download',
      'download_all': 'Download all',
      'download_queued': 'Added to download queue',
      'download_already_queued': 'Already downloaded or in the download queue.',
      'spotify_playlist_load_failed':
          'Spotify playlist songs could not be loaded.',
      'playback_failed': 'Playback failed',
      'more': 'More options',
      'wrong_match': 'Wrong match?',
      'find_alternative': 'Find alternative',
      'no_alternatives': 'No alternatives found',
      'album_discovery': 'Discover',
      'new_releases': 'New Releases',
      'browse_genre': 'Browse by Genre',
      'artist_profile': 'Artist',
      'related_artists': 'Related Artists',
      'discography': 'Discography',
      'play_all': 'Play All',
      'followers': 'followers',
      'following': 'Following',
      'follow': 'Follow',
      'unfollow': 'Unfollow',
      'save': 'Save',
      'sync_settings': 'Sync Settings',
      'sync_this_playlist': 'Sync this playlist',
      'sync_direction': 'Direction',
      'spotify_to_yt': 'Spotify → YT Music',
      'yt_to_spotify': 'YT Music → Spotify',
      'bidirectional': 'Bidirectional',
      'sync_now': 'Sync Now',
      'last_synced': 'Last synced',
      'default_sync': 'Default Sync',
      'syncing_enabled': 'Syncing',
      'metadata_backfill': 'Metadata',
      'backfill_art': 'Backfill Album Art',
      'backfill_lyrics': 'Backfill Lyrics',
      'backfill_all': 'Backfill All',
      'high_res_art': 'High-Res Album Art',
      'lyrics': 'Lyrics',
      'backfill_progress': 'Progress',
      'last_backfilled': 'Last backfilled',
      'lossless': 'Lossless',
      'lossless_quality': 'Lossless Quality',
      'embed_metadata': 'Embed Metadata',
      'cover_resolution': 'Cover Resolution',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'loudness_norm': 'Loudness Normalization',
      'downloads': 'Downloads',
      'active': 'Active',
      'completed': 'Completed',
      'failed': 'Failed',
      'retry': 'Retry',
      'retry_all': 'Retry All',
      'clear_all': 'Clear All',
      'no_downloads': 'No downloads',
      'no_failed_downloads': 'No failed downloads',
      'download_progress': 'Progress',
      'download_location': 'Download Location',
      'match_confidence': 'Match Confidence',
      'exact_match': 'Exact Match',
      'fuzzy_match': 'Fuzzy Match',
      'manual_match': 'Manual Match',
      'rematch_all': 'Rematch All',
      'match_progress': 'Matching',
      'resolving': 'Resolving source...',
      'downloading_file': 'Downloading...',
      'embedding': 'Embedding metadata...',
      'minutes': 'min',
      'timer_active': 'Timer active',
      'cancel_timer': 'Cancel Timer',
      'timer_ended': 'Playback paused',
      'reset_eq': 'Reset',
      'normal': 'Normal',
      'pop': 'Pop',
      'rock': 'Rock',
      'jazz': 'Jazz',
      'classical': 'Classical',
      'vocal': 'Vocal',
      'custom_eq': 'Custom',
      'blocklist': 'Blocked Tracks',
      'block_track': 'Block',
      'unblock': 'Unblock',
      'no_blocked_tracks': 'No blocked tracks',
      'no_shared_links': 'No shared links yet',
      'blocked_count': 'Blocked',
      'scheduled_sync': 'Scheduled Sync',
      'sync_days': 'Sync Days',
      'next_sync': 'Next sync',
      'run_sync_now': 'Sync Now',
      'sync_enabled': 'Auto Sync',
      'library_size': 'Library Size',
      'clear_cache': 'Clear Cache',
      'move_library': 'Move Library',
      'storage_location': 'Location',
      'format_breakdown': 'Format Breakdown',
      'used_space': 'Used',
      'free_space': 'Free',
      'monday': 'Mon',
      'tuesday': 'Tue',
      'wednesday': 'Wed',
      'thursday': 'Thu',
      'friday': 'Fri',
      'saturday': 'Sat',
      'sunday': 'Sun',
      'spotify_cookie_login': 'Cookie Login',
      'sp_dc_label': 'sp_dc cookie',
      'sp_key_label': 'sp_key cookie',
      'yt_cookie_login': 'YouTube Cookie Login',
      'yt_cookie_label': 'Cookie string',
      'cookie_auth_desc': 'Paste cookies from browser',
      'listening_stats': 'Listening Stats',
      'total_plays': 'Total Plays',
      'total_listening_time': 'Listening Time',
      'unique_artists': 'Unique Artists',
      'audio_quality': 'Audio Quality',
      'streaming_quality': 'Streaming',
      'download_quality': 'Downloads',
      'cellular_quality': 'Cellular',
      'wifi_quality': 'WiFi',
      'quality_auto': 'Auto',
      'quality_low': 'Low',
      'quality_normal': 'Normal',
      'quality_high': 'High',
      'quality_lossless': 'Lossless',
      'file_organization': 'File Organization',
      'organized_by_artist': 'By Artist/Album',
      'flat_structure': 'Flat',
      'organize_now': 'Organize Now',
      'keep_downloads': 'Keep Downloads',
      'auto_delete': 'Auto-delete after',
      'never': 'Never',
      'days': 'days',
      'storage_management': 'Storage Management',
      'preview': 'Preview',
      'library_health': 'Library Health',
      'health_score': 'Health',
      'scan_library': 'Scan Library',
      'rescan': 'Rescan',
      'fix_all': 'Fix All',
      'issues_found': 'issues found',
      'no_issues': 'Library is healthy!',
      'missing_art': 'Missing Album Art',
      'missing_metadata': 'Missing Metadata',
      'failed_downloads_issue': 'Failed Downloads',
      'low_confidence': 'Low Match Confidence',
      'duplicates': 'Duplicate Tracks',
      'orphaned_files': 'Orphaned Files',
      'x_tracks_need_art': '{count} tracks need album art',
      'x_tracks_need_lyrics': '{count} tracks need lyrics',
      'x_tracks_waiting_lossless': '{count} tracks waiting for lossless',
      'x_downloads_failed': '{count} downloads failed',
      'stream_cache': 'Stream Cache',
      'cache_size': 'Cache Size',
      'resume_playback': 'Resume Playback',
      'cache_cleared': 'Cache Cleared',
      'quick_access': 'QUICK ACCESS',
      'recently_played_subtitle': 'Recently played songs',
      'liked_songs_subtitle': 'Songs you liked',
      'downloads_subtitle': 'Downloaded songs',
      'scrobbling_subtitle': 'Listening history',
      'listening_history': 'Listening History',
      'calendar': 'Calendar',
      'statistics': 'Statistics',
      'suggestions': 'Suggestions',
      'no_listening_history': 'No listening history for this date',
      'top_tracks': 'Top Tracks',
      'top_artists': 'Top Artists',
      'time_based_suggestion': 'Time-based Suggestions',
      'recent_favorites': 'Recent Favorites',
      'top_this_week': 'Top This Week',
      'not_enough_data': 'Not enough data for suggestions',
      'times': 'times',
      'morning_suggestion': 'Morning mood',
      'afternoon_suggestion': 'Afternoon energy',
      'evening_suggestion': 'Evening vibes',
      'night_suggestion': 'Late night sessions',
      // Onboarding
      'welcome_to_melodi': 'Welcome to\nMelodi',
      'onboarding_welcome_desc':
          'Your personal music companion.\nBeautiful, fast, and built for you.',
      'choose_language': 'Choose\nLanguage',
      'onboarding_language_desc':
          'Select your preferred language.\nYou can change this later in settings.',
      'choose_theme': 'Choose\nTheme',
      'onboarding_theme_desc':
          'Pick a look that suits your style.\nDark or light — you decide.',
      'connect_services': 'Connect\nServices',
      'onboarding_services_desc':
          'Link your streaming accounts to\nimport playlists and sync your plays.',
      'get_started': 'Get Started',
      'skip': 'Skip',
      'next': 'Continue',
      'import_playlists': 'Import your playlists',
      'import_songs': 'Sync your music library',
      'connect_for_scrobbling': 'Track your listening history',
      'spotify_subtitle': 'Import playlists & liked songs',
      'youtube_subtitle': 'Sync your music library',
      // Greetings
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'general': 'General',
      // Accent color names
      'color_spotify_green': 'Spotify Green',
      'color_green': 'Green',
      'color_red': 'Red',
      'color_pink': 'Pink',
      'color_blue': 'Blue',
      'color_indigo': 'Indigo',
      'color_purple': 'Purple',
      'color_orange': 'Orange',
      'color_yellow': 'Yellow',
      'color_mint': 'Mint',
      'color_teal': 'Teal',
      'color_white': 'White',
      'color_rose': 'Rose',
      'color_deep_purple': 'Deep Purple',
      'color_light_blue': 'Light Blue',
      'color_cyan': 'Cyan',
      'color_material_green': 'Material Green',
      'color_deep_orange': 'Deep Orange',
      'color_brown': 'Brown',
      'color_blue_grey': 'Blue Grey',
      // Equalizer presets
      'preset_flat': 'Flat',
      'preset_classical': 'Classical',
      'preset_dance': 'Dance',
      'preset_acoustic': 'Acoustic',
      'preset_bass_boost': 'Bass Boost',
      'preset_treble_boost': 'Treble Boost',
      'preset_loudness': 'Loudness',
      'preset_rock': 'Rock',
      'preset_pop': 'Pop',
      'preset_jazz': 'Jazz',
      'preset_voice': 'Voice',
      'preset_custom': 'Custom',
      // Library
      'liked_songs_label': 'Liked Songs',
      'recently_played': 'Recently Played',
      'sort_by_recent': 'By Recently Played',
      'sort_by_name': 'By Name',
      'sort_by_date': 'By Date',
      'playlist_count': 'Playlist • {count} songs',
      'artist_count': 'Artist • {count} songs',
      'album_count': 'Album • {count}',
      // Create playlist
      'create': 'Create',
      'create_playlist_button': 'Create Playlist',
      'add_cover_photo': 'Add Cover Photo',
      'enter_playlist_name': 'Enter playlist name',
      'description': 'Description',
      'optional_description': 'Optional description',
      'privacy': 'Privacy',
      'private_playlist': 'Private playlist',
      'high_fidelity_active': 'High fidelity experience active',
      // Audio settings
      'audio_effects': 'Audio Effects',
      'audio_effects_desc': 'Spatial audio, reverb, bass boost',
      'spatial_audio': 'Spatial Audio',
      'spatial_audio_desc': '3D sound positioning',
      'reverb': 'Reverb',
      'reverb_desc': 'Add room ambience effects',
      'bass_boost': 'Bass Boost',
      'bass_boost_desc': 'Enhance low frequency response',
      'virtualizer': 'Virtualizer',
      'virtualizer_desc': 'Simulate surround sound through headphones',
      'eq_presets': 'EQ Presets',
      'eq_presets_desc': 'Choose from preset equalizer profiles',
      'gapless_playback_setting': 'Gapless Playback',
      'gapless_playback_desc': 'Seamless transitions between tracks',
      'bluetooth_auto_eq': 'Bluetooth Auto-EQ',
      'bluetooth_auto_eq_desc': 'Automatically adjust EQ for Bluetooth devices',
      'siri_shortcuts': 'Siri Shortcuts',
      'siri_shortcuts_desc': 'Configure voice control shortcuts',
      'siri_integration': 'Siri Integration',
      'siri_integration_desc': 'Control playback with Siri commands',
      'custom_shortcuts': 'Custom Shortcuts',
      'custom_shortcuts_desc': 'Create custom voice commands',
      'siri_shortcuts_info':
          'Siri Shortcuts are managed in iOS Settings > Siri & Search',
      'voice_feedback': 'Voice Feedback',
      'voice_feedback_desc': 'Announce track changes and status',
      'voice_control': 'Voice Control',
      'shared_links': 'Shared Links',
      'no_audiobooks_found': 'No audiobooks found',
      'import_audiobooks_hint': 'Start by importing from a folder',
      'local_results': 'Local Results',
      'online_results': 'Online Results',
      'no_results': 'No results found',
      'playing_genre': 'Playing {genre} songs',
      'no_genre_songs': 'No {genre} songs in your library',
      'mix_artist': 'Mix: {artist}',
      'daily_mix': 'Daily Mix {number}',
      'airplay': 'AirPlay',
      'airplay_desc': 'Stream to available AirPlay devices',
      'podcast': 'Podcast',
      'podcast_desc': 'Manage podcast subscriptions',
      'audiobook': 'Audiobook',
      'audiobook_desc': 'Browse audiobook library',
      'widget': 'Widget',
      'widget_desc': 'Configure home screen widgets',
      // Splash
      'signal_path_preparing': 'Preparing your experience...',
      'scanning_library': 'Scanning library...',
      'enjoy_listening': 'Enjoy listening!',
      'import_playlist': 'Import Playlist',
      'import_playlist_hint':
          'Paste a Spotify, YouTube Music or Deezer playlist link. Songs are matched and can be streamed/downloaded online.',
      'playlist_name': 'Playlist Name',
      'importing': 'Importing...',
      'import': 'Import',
      'playlist_imported': 'Playlist imported.',
    },
    'tr': {
      'home': 'Ana Sayfa',
      'library': 'Kitaplık',
      'search': 'Ara',
      'settings': 'Ayarlar',
      'now_playing': 'Şimdi Çalıyor',
      'no_song_playing': 'Şarkı çalmıyor',
      'no_music_playing': 'Müzik çalmıyor',
      'your_music_awaits': 'Müziğiniz sizi bekliyor',
      'import_songs_to_start': 'Başlamak için cihazınızdan şarkı içe aktarın',
      'import_music': 'Müzik İçe Aktar',
      'liked_songs': 'Beğenilen Şarkılar',
      'albums': 'Albümler',
      'popular_artists': 'Popüler Sanatçılar',
      'playlists': 'Çalma Listeleri',
      'see_all': 'Tümünü Gör',
      'your_top_mixes': 'Karıştırma Listelerin',
      'recently_added': 'Son Eklenenler',
      'songs': 'Şarkılar',
      'artists': 'Sanatçılar',
      'genres': 'Türler',
      'sort_by_title': 'Başlığa Göre Sırala',
      'sort_by_artist': 'Sanatçıya Göre Sırala',
      'sort_by_album': 'Albüme Göre Sırala',
      'sort_by_duration': 'Süreye Göre Sırala',
      'sort_by_date_added': 'Eklenme Tarihine Göre Sırala',
      'no_albums_found': 'Albüm bulunamadı',
      'no_artists_found': 'Sanatçı bulunamadı',
      'no_genres_found': 'Tür bulunamadı',
      'your_library_is_empty': 'Kitaplığınız boş',
      'import_music_from_device': 'Cihazınızdan müzik içe aktarın',
      'scan_music_library': 'Müzik Kitaplığını Tara',
      'what_to_listen': 'Ne dinlemek istersiniz?',
      'recent_searches': 'Son Aramalar',
      'clear': 'Temizle',
      'browse_all': 'Tümünü Keşfet',
      'no_results_for': 'için sonuç bulunamadı',
      'queue': 'Sıra',
      'queue_is_empty': 'Sıra boş',
      'add_songs': 'Şarkı Ekle',
      'all_songs_added': 'Tüm şarkılar zaten eklendi',
      'add_songs_to_start': 'Çalmaya başlamak için şarkı ekleyin',
      'add_to_playlist': 'Çalma Listesine Ekle',
      'song_info': 'Şarkı Bilgisi',
      'share': 'Paylaş',
      'sleep_timer': 'Uyku Zamanlayıcı',
      'no_playlists_yet': 'Henüz çalma listeniz yok. Önce bir tane oluşturun.',
      'create_new_playlist': 'Yeni Çalma Listesi Oluştur',
      'new_playlist': 'Yeni Çalma Listesi',
      'playlist_name': 'Çalma listesi adı',
      'cancel': 'İptal',
      'close': 'Kapat',
      'rename_playlist': 'Çalma Listesini Yeniden Adlandır',
      'delete_playlist': 'Çalma Listesini Sil',
      'rename': 'Yeniden Adlandır',
      'delete': 'Sil',
      'delete_playlist_warning': 'Silmek istediğinize emin misiniz',
      'no_songs_in_playlist': 'Bu çalma listesinde şarkı yok',
      'add_songs_from_library': 'Kitaplıktan şarkı ekleyin',
      'play': 'Oynat',
      'appearance': 'Görünüm',
      'theme': 'Tema',
      'theme_mode': 'Tema Modu',
      'custom_colors': 'Özel Renkler',
      'dark': 'Koyu',
      'light': 'Açık',
      'system': 'Sistem',
      'language': 'Dil',
      'app_language': 'Uygulama Dili',
      'music_library': 'Müzik Kitaplığı',
      'rescan_library': 'Kitaplığı Yeniden Tara',
      'scan_device_for_music': 'Yeni veya kaldırılan müzikler için cihazı tara',
      'import_from_files': 'Dosyalardan İçe Aktar',
      'browse_and_import': 'Ses dosyalarına göz atın ve içe aktarın',
      'import_from_folder': 'Klasörden İçe Aktar',
      'scan_folder_for_music': 'Müzik için belirli bir klasörü tara',
      'storage': 'Depolama',
      'local_songs': 'Yerel Şarkılar',
      'songs_in_library': 'kitaplıkta şarkı',
      'clear_library': 'Kitaplığı Temizle',
      'remove_cached_data': 'Tüm önbelleğe alınmış müzik verilerini kaldır',
      'clear_library_title': 'Kitaplığı Temizle',
      'clear_library_confirm':
          'Bu, tüm önbelleğe alınmış müzik verilerini kaldıracaktır. Gerçek müzik dosyalarınız silinmeyecektir.',
      'audio': 'Ses',
      'equalizer': 'Ekolayzır',
      'adjust_sound_frequencies': 'Ses frekanslarını ayarlayın',
      'equalizer_coming_soon': 'Ekolayzır çok yakında',
      'equalizer_not_available': 'Ekolayzır bu cihazda mevcut değil',
      'accounts': 'Hesaplar',
      'connected_as': 'Bağlı:',
      'disconnect': 'Bağlantıyı Kes',
      'spotify': 'Spotify',
      'connect_spotify_description':
          'Spotify çalma listelerini ve beğenilen şarkılarını içe aktar. Tarayıcı çerezinle bağlan.',
      'spotify_cookie_instructions':
          '1. Tarayıcıda open.spotify.com\'a gidin\n2. Giriş yapın\n3. DevTools (F12) > Application > Cookies bölümünü açın\n4. "sp_dc" değerini kopyalayın\n5. Aşağıya yapıştırın',
      'paste_sp_dc_cookie': 'sp_dc çerezini yapıştır',
      'import_liked_songs': 'Beğenilen Şarkıları İçe Aktar',
      'spotify_connected_as': 'Bağlandı:',
      'enter_spotify_username': 'Spotify kullanıcı adı (isteğe bağlı)',
      'connect_spotify': 'Spotify kitaplığını bağla',
      'i_authorized': 'Yetkilendirdim',
      'auth_failed_try_again':
          'Yetkilendirme başarısız. Lütfen tekrar deneyin.',
      'presets': 'Ön Ayarlar',
      'default_playback_speed': 'Varsayılan Oynatma Hızı',
      'volume_boost': 'Ses Güçlendirme',
      'playback': 'Oynatma',
      'auto_shuffle': 'Otomatik Karıştır',
      'automatically_shuffle': 'Çalarken otomatik olarak karıştır',
      'gapless_playback': 'Kesintisiz Oynatma',
      'seamless_transition': 'Şarkılar arasında kesintisiz geçiş',
      'crossfade': 'Çapraz Geçiş',
      'seconds_crossfade': 'sn çapraz geçiş',
      'off': 'Kapalı',
      'apply': 'Uygula',
      'about': 'Hakkında',
      'version': 'Sürüm',
      'built_with_flutter': 'Flutter ve Sevgiyle Yapıldı',
      'acknowledgments': 'Teşekkürler',
      'credits': 'Katkıda Bulunanlar',
      'open_source_licenses': 'Açık kaynak bileşenler ve lisanslar',
      'developer': 'Geliştirici',
      'repeat_all': 'Tümünü Tekrarla',
      'repeat_one': 'Birini Tekrarla',
      'shuffled': 'Karıştır',
      'added_to': 'eklendi',
      'created_and_added_to': 'Oluşturuldu ve eklendi',
      'no_songs': 'Şarkı yok',
      'english': 'İngilizce',
      'turkish': 'TÜRKÇE',
      'german': 'Almanca',
      'scan_media_library': 'Medya Kitaplığını Tara',
      'import_from_apple_music': 'Apple Music kitaplığından içe aktar',
      'browse_files': 'Dosyalara Göz At',
      'select_audio_files': 'Dosyalar uygulamasından ses dosyaları seçin',
      'import_from_folder_title': 'Klasörden İçe Aktar',
      'scan_specific_folder': 'Belirli bir klasörü tara',
      'seconds': 'saniye',
      'melodi': 'Melodi',
      'add_to_queue': 'Sıraya Ekle',
      'play_next': 'Sıradaki',
      'view_album': 'Albümü Gör',
      'view_artist': 'Sanatçıyı Gör',
      'watched_folder': 'İzlenen Klasör',
      'auto_scan_folder': 'Her açılışta bir klasörü otomatik tara',
      'watching': 'İzleniyor',
      'folder_set': 'Klasör ayarlandı',
      'could_not_open_link': 'Link açılamadı',
      'youtube_search_hint': 'YouTube\'da ara',
      'downloading': 'İndiriliyor...',
      'download_complete': 'İndirme tamamlandı',
      'download_failed': 'İndirme başarısız',
      'loading_song': 'Yükleniyor',
      'sleep_timer_canceled': 'Uyku zamanlayıcı kapatıldı',
      'output_selection': 'Ses çıkışı seçimi yakında',
      'device_selection': 'Cihaz seçimi yakında',
      'artist_label': 'Sanatçı',
      'album_label': 'Albüm',
      'genre_label': 'Tür',
      'year_label': 'Yıl',
      'track_label': 'Parça',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Süre',
      'file_label': 'Dosya',
      'accent_color': 'Vurgu Rengi',
      'tap_to_change': 'Değiştirmek için dokunun',
      'background': 'Arka Plan',
      'surface': 'Yüzey',
      'card': 'Kart',
      'text_primary': 'Birincil Metin',
      'text_secondary': 'İkincil Metin',
      'reset_colors': 'Renkleri Sıfırla',
      'default_color': 'Varsayılan',
      'create_playlist': 'Çalma Listesi Oluştur',
      'share_song': 'Şarkıyı Paylaş',
      'share_file': 'Ses Dosyasını Paylaş',
      'now_playing_queue': 'Sıradan Çalıyor',
      'song_count': 'şarkı',
      'min': 'dk',
      'hr': 'sa',
      'dynamic_colors': 'Dinamik Renkler',
      'apply_album_colors': 'Albüm kapağından renkleri uygula',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description':
          'YouTube Music kitaplığınızı içe aktarın. Tarayıcı çerezinizle bağlanın.',
      'ytmusic_cookie_instructions':
          '1. Tarayıcıda music.youtube.com adresine gidin\n2. Giriş yapın\n3. Geliştirici Araçları (F12) > Application > Cookies bölümünü açın\n4. "__Secure-3PSAPISID" değerini kopyalayın\n5. Aşağıya yapıştırın',
      'paste_ytmusic_cookie': 'SAPISID çerezini yapıştır',
      'import_albums': 'Albümleri İçe Aktar',
      'connect_youtube_music': 'YouTube Music bağla',
      'auto_sync': 'Otomatik Senkronizasyon',
      'sync_time': 'Senkronizasyon Zamanı',
      'wifi_only': 'Sadece Wi-Fi',
      'sync_schedule': 'Senkronizasyon Takvimi',
      'online_mode': 'Çevrimiçi Mod',
      'offline_mode': 'Çevrimdışı Mod',
      'stream_on_cellular': 'Mobil Veride Akış',
      'streaming': 'Akış',
      'synced_lyrics': 'Senkronize Şarkı Sözleri',
      'no_lyrics': 'Şarkı sözü yok',
      'instrumental': 'Enstrümantal',
      'login_with_browser': 'Tarayıcı ile Giriş Yap',
      'cookie_paste': 'veya çerezi elle yapıştır',
      'like_mirroring': 'Beğeni Senkronizasyonu',
      'mirror_likes': 'Beğenileri Senkronize Et',
      'mirroring_enabled': 'Senkronizasyon açık',
      'mirrored_count': 'Senkronize Edilen',
      'mirror_now': 'Şimdi Senkronize Et',
      'last_mirrored': 'Son senkronizasyon',
      'mirror_likes_description':
          'Spotify ve YouTube Music arasında beğenileri senkronize tut',
      'mixes': 'Karışımlar',
      'release_radar': 'Yayın Radarı',
      'discover_weekly': 'Haftalık Keşif',
      'regenerate': 'Yeniden Oluştur',
      'no_mixes_yet': 'Henüz karışım oluşturulmadı',
      'generated_at': 'Oluşturulma',
      'diagnostics': 'Tanılama',
      'export_diagnostics': 'Dışa Aktar',
      'clear_logs': 'Günlükleri Temizle',
      'error_logs': 'Hata Günlükleri',
      'service_status': 'Hizmet Durumu',
      'app_info': 'Uygulama Bilgisi',
      'crash_reports': 'Çökme Raporları',
      'scrobbling': 'Scrobbling',
      'yt_history_scrobbling': 'YouTube Geçmişi Aktarma',
      'scrobble_now': 'Şimdi Aktar',
      'scrobbled_count': 'Aktarılan',
      'scrobbling_enabled': 'Otomatik aktarma',
      'last_scrobbled': 'Son aktarma',
      'recent_scrobbles': 'Son Aktarılanlar',
      'auth_expired': 'Bağlantı Süresi Doldu',
      'reconnect': 'Yeniden Bağlan',
      'auth_expired_desc':
          '{service} bağlantınızın süresi doldu. Yeniden bağlanmak için dokunun.',
      'streaming_prompt_title': 'Akış Modu',
      'streaming_prompt_body':
          'Bu parça indirme gerektiriyor. Akış yapmak ister misiniz?',
      'stream': 'Akış',
      'download': 'İndir',
      'download_all': 'Tümünü indir',
      'download_queued': 'İndirme kuyruğuna eklendi',
      'download_already_queued': 'Zaten indirildi veya indirme kuyruğunda.',
      'spotify_playlist_load_failed':
          'Spotify çalma listesindeki şarkılar yüklenemedi.',
      'playback_failed': 'Oynatma başarısız',
      'more': 'Diğer seçenekler',
      'wrong_match': 'Yanlış eşleşme?',
      'find_alternative': 'Alternatif bul',
      'no_alternatives': 'Alternatif bulunamadı',
      'album_discovery': 'Keşfet',
      'new_releases': 'Yeni Çıkanlar',
      'browse_genre': 'Türe Göre Gözat',
      'artist_profile': 'Sanatçı',
      'related_artists': 'Benzer Sanatçılar',
      'discography': 'Diskografi',
      'play_all': 'Tümünü Oynat',
      'followers': 'takipçi',
      'following': 'Takip Ediliyor',
      'follow': 'Takip Et',
      'unfollow': 'Takipten Çık',
      'save': 'Kaydet',
      'sync_settings': 'Senkronizasyon Ayarları',
      'sync_this_playlist': 'Bu listeyi senkronize et',
      'sync_direction': 'Yön',
      'spotify_to_yt': 'Spotify → YT Music',
      'yt_to_spotify': 'YT Music → Spotify',
      'bidirectional': 'Çift Yönlü',
      'sync_now': 'Şimdi Senkronize Et',
      'last_synced': 'Son senkronizasyon',
      'default_sync': 'Varsayılan Senkronizasyon',
      'syncing_enabled': 'Senkronizasyon',
      'metadata_backfill': 'Metaveri',
      'backfill_art': 'Albüm Kapaklarını Doldur',
      'backfill_lyrics': 'Şarkı Sözlerini Doldur',
      'backfill_all': 'Tümünü Doldur',
      'high_res_art': 'Yüksek Çözünürlüklü Kapak',
      'lyrics': 'Şarkı Sözleri',
      'backfill_progress': 'İlerleme',
      'last_backfilled': 'Son doldurma',
      'lossless': 'Kayıpsız',
      'lossless_quality': 'Kayıpsız Kalite',
      'embed_metadata': 'Metaveri Göm',
      'cover_resolution': 'Kapak Çözünürlüğü',
      'high': 'Yüksek',
      'medium': 'Orta',
      'low': 'Düşük',
      'loudness_norm': 'Ses Normalleştirme',
      'downloads': 'İndirilenler',
      'active': 'Aktif',
      'completed': 'Tamamlanan',
      'failed': 'Başarısız',
      'retry': 'Tekrar Dene',
      'retry_all': 'Tümünü Dene',
      'clear_all': 'Tümünü Temizle',
      'no_downloads': 'İndirme yok',
      'no_failed_downloads': 'Başarısız indirme yok',
      'download_progress': 'İlerleme',
      'download_location': 'İndirme Konumu',
      'match_confidence': 'Eşleşme Güveni',
      'exact_match': 'Tam Eşleşme',
      'fuzzy_match': 'Benzer Eşleşme',
      'manual_match': 'Manuel Eşleşme',
      'rematch_all': 'Tümünü Yeniden Eşleştir',
      'match_progress': 'Eşleşiyor',
      'resolving': 'Kaynak çözülüyor...',
      'downloading_file': 'İndiriliyor...',
      'embedding': 'Metaveri gömülüyor...',
      'minutes': 'dk',
      'timer_active': 'Zamanlayıcı aktif',
      'cancel_timer': 'Zamanlayıcıyı İptal Et',
      'timer_ended': 'Oynatma durduruldu',
      'reset_eq': 'Sıfırla',
      'normal': 'Normal',
      'pop': 'Pop',
      'rock': 'Rock',
      'jazz': 'Caz',
      'classical': 'Klasik',
      'vocal': 'Vokal',
      'custom_eq': 'Özel',
      'blocklist': 'Engellenen Parçalar',
      'block_track': 'Engelle',
      'unblock': 'Engeli Kaldır',
      'no_blocked_tracks': 'Engellenen parça yok',
      'no_shared_links': 'Henüz paylaşılan bağlantı yok',
      'blocked_count': 'Engellenen',
      'scheduled_sync': 'Planlı Senkronizasyon',
      'sync_days': 'Senkronizasyon Günleri',
      'next_sync': 'Sonraki Senk.',
      'run_sync_now': 'Şimdi Senk.',
      'sync_enabled': 'Otomatik Senk.',
      'library_size': 'Kütüphane Boyutu',
      'clear_cache': 'Önbelleği Temizle',
      'move_library': 'Kütüphaneyi Taşı',
      'storage_location': 'Konum',
      'format_breakdown': 'Format Dağılımı',
      'used_space': 'Kullanılan',
      'free_space': 'Boş',
      'monday': 'Pzt',
      'tuesday': 'Sal',
      'wednesday': 'Çar',
      'thursday': 'Per',
      'friday': 'Cum',
      'saturday': 'Cmt',
      'sunday': 'Paz',
      'spotify_cookie_login': 'Çerez Girişi',
      'sp_dc_label': 'sp_dc çerezi',
      'sp_key_label': 'sp_key çerezi',
      'yt_cookie_login': 'YouTube Çerez Girişi',
      'yt_cookie_label': 'Çerez metni',
      'cookie_auth_desc': 'Tarayıcıdan çerezleri yapıştır',
      'listening_stats': 'Dinleme İstatistikleri',
      'total_plays': 'Toplam Dinleme',
      'total_listening_time': 'Dinleme Süresi',
      'unique_artists': 'Farklı Sanatçı',
      'audio_quality': 'Ses Kalitesi',
      'streaming_quality': 'Akış',
      'download_quality': 'İndirme',
      'cellular_quality': 'Hücresel',
      'wifi_quality': 'WiFi',
      'quality_auto': 'Otomatik',
      'quality_low': 'Düşük',
      'quality_normal': 'Normal',
      'quality_high': 'Yüksek',
      'quality_lossless': 'Kayıpsız',
      'file_organization': 'Dosya Düzeni',
      'organized_by_artist': 'Sanatçı/Albüme Göre',
      'flat_structure': 'Düz',
      'organize_now': 'Şimdi Düzenle',
      'keep_downloads': 'İndirmeleri Sakla',
      'auto_delete': 'Otomatik silme',
      'never': 'Asla',
      'days': 'gün',
      'storage_management': 'Depolama Yönetimi',
      'preview': 'Önizleme',
      'library_health': 'Kütüphane Sağlığı',
      'health_score': 'Sağlık',
      'scan_library': 'Kütüphaneyi Tara',
      'rescan': 'Yeniden Tara',
      'fix_all': 'Tümünü Düzelt',
      'issues_found': 'sorun bulundu',
      'no_issues': 'Kütüphane sağlıklı!',
      'missing_art': 'Eksik Albüm Kapağı',
      'missing_metadata': 'Eksik Metaveri',
      'failed_downloads_issue': 'Başarısız İndirmeler',
      'low_confidence': 'Düşük Eşleşme',
      'duplicates': 'Tekrar Eden Parçalar',
      'orphaned_files': 'Yetim Dosyalar',
      'x_tracks_need_art': '{count} parça albüm kapağı bekliyor',
      'x_tracks_need_lyrics': '{count} parça şarkı sözü bekliyor',
      'x_tracks_waiting_lossless': '{count} parça kayıpsız bekliyor',
      'x_downloads_failed': '{count} indirme başarısız',
      'stream_cache': 'Akış Önbelleği',
      'cache_size': 'Önbellek Boyutu',
      'resume_playback': 'Kaldığından Devam',
      'cache_cleared': 'Önbellek Temizlendi',
      'quick_access': 'HIZLI ERİŞİM',
      'recently_played_subtitle': 'Son çalınan şarkılar',
      'liked_songs_subtitle': 'Beğendiğin şarkılar',
      'downloads_subtitle': 'İndirilen şarkılar',
      'scrobbling_subtitle': 'Dinleme geçmişi',
      'listening_history': 'Dinleme Geçmişi',
      'calendar': 'Takvim',
      'statistics': 'İstatistikler',
      'suggestions': 'Öneriler',
      'no_listening_history': 'Bu tarih için dinleme geçmişi yok',
      'top_tracks': 'En Çok Dinlenen Şarkılar',
      'top_artists': 'En Çok Dinlenen Sanatçılar',
      'time_based_suggestion': 'Zamana Göre Öneriler',
      'recent_favorites': 'Son Favoriler',
      'top_this_week': 'Bu Haftanın Enleri',
      'not_enough_data': 'Öneriler için yeterli veri yok',
      'times': 'kez',
      'morning_suggestion': 'Sabah ruh hali',
      'afternoon_suggestion': 'Öğleden sonra enerjisi',
      'evening_suggestion': 'Akşam havası',
      'night_suggestion': 'Gece seansları',
      // Onboarding
      'welcome_to_melodi': 'Melodi\'ye Hoş Geldin',
      'onboarding_welcome_desc':
          'Kişisel müzik dostun. Güzel, hızlı ve senin için tasarlandı.',
      'choose_language': 'Dil Seçin',
      'onboarding_language_desc':
          'Tercih ettiğiniz dili seçin. Daha sonra değiştirebilirsiniz.',
      'choose_theme': 'Tema Seçin',
      'onboarding_theme_desc':
          'Size uygun görünümü seçin.\nKoyu veya açık — size kalmış.',
      'connect_services': 'Hesapları\nBağlayın',
      'onboarding_services_desc':
          'Çalma listelerinizi içe aktarmak ve\ndinleme geçmişinizi senkronize etmek için hesaplarınızı bağlayın.',
      'get_started': 'Başla',
      'skip': 'Atla',
      'next': 'Devam',
      'import_playlists': 'Çalma listelerinizi aktarın',
      'import_songs': 'Müzik kütüphanenizi senkronize edin',
      'connect_for_scrobbling': 'Dinleme geçmişinizi takip edin',
      'spotify_subtitle': 'Çalma listeleri ve beğenilen şarkılar',
      'youtube_subtitle': 'Müzik kütüphanenizi senkronize edin',
      // Greetings
      'good_morning': 'Günaydın',
      'good_afternoon': 'İyi Günler',
      'good_evening': 'İyi Akşamlar',
      'general': 'Genel',
      // Accent color names
      'color_spotify_green': 'Spotify Yeşil',
      'color_green': 'Yeşil',
      'color_red': 'Kırmızı',
      'color_pink': 'Pembe',
      'color_blue': 'Mavi',
      'color_indigo': 'İndigo',
      'color_purple': 'Mor',
      'color_orange': 'Turuncu',
      'color_yellow': 'Sarı',
      'color_mint': 'Nane',
      'color_teal': 'Deniz',
      'color_white': 'Beyaz',
      'color_rose': 'Gül',
      'color_deep_purple': 'Koyu Mor',
      'color_light_blue': 'Açık Mavi',
      'color_cyan': 'Cyan',
      'color_material_green': 'Material Yeşil',
      'color_deep_orange': 'Koyu Turuncu',
      'color_brown': 'Kahverengi',
      'color_blue_grey': 'Mavi Gri',
      // Equalizer presets
      'preset_flat': 'Düz',
      'preset_classical': 'Klasik',
      'preset_dance': 'Dans',
      'preset_acoustic': 'Akustik',
      'preset_bass_boost': 'Bas Güçlendirme',
      'preset_treble_boost': 'Tiz Güçlendirme',
      'preset_loudness': 'Ses Seviyesi',
      'preset_rock': 'Rock',
      'preset_pop': 'Pop',
      'preset_jazz': 'Caz',
      'preset_voice': 'Ses',
      'preset_custom': 'Özel',
      // Library
      'liked_songs_label': 'Beğenilen Şarkılar',
      'recently_played': 'Son Çalınanlar',
      'sort_by_recent': 'Son Çalınanlara Göre',
      'sort_by_name': 'İsme Göre',
      'sort_by_date': 'Tarihe Göre',
      'playlist_count': 'Çalma Listesi • {count} şarkı',
      'artist_count': 'Sanatçı • {count} şarkı',
      'album_count': 'Albüm • {count}',
      // Create playlist
      'create': 'Oluştur',
      'create_playlist_button': 'Çalma Listesi Oluştur',
      'add_cover_photo': 'Kapak Fotoğrafı Ekle',
      'enter_playlist_name': 'Çalma listesi adını girin',
      'description': 'Açıklama',
      'optional_description': 'İsteğe bağlı açıklama',
      'privacy': 'Gizlilik',
      'private_playlist': 'Özel çalma listesi',
      'high_fidelity_active': 'Yüksek kalite deneyimi aktif',
      // Audio settings
      'audio_effects': 'Ses Efektleri',
      'audio_effects_desc': 'Uzamsal ses, yankı, bas güçlendirme',
      'spatial_audio': 'Uzamsal Ses',
      'spatial_audio_desc': '3D ses konumlandırma',
      'reverb': 'Yankı',
      'reverb_desc': 'Oda atmosferi efektleri ekle',
      'bass_boost': 'Bas Güçlendirme',
      'bass_boost_desc': 'Düşük frekans yanıtını geliştir',
      'virtualizer': 'Sanal Ses',
      'virtualizer_desc': 'Kulaklıkla surround ses simülasyonu',
      'eq_presets': 'EQ Ön Ayarları',
      'eq_presets_desc': 'Ön ayarlı ekolayzır profillerinden seçim yapın',
      'gapless_playback_setting': 'Kesintisiz Oynatma',
      'gapless_playback_desc': 'Parçalar arasında kesintisiz geçiş',
      'bluetooth_auto_eq': 'Bluetooth Otomatik EQ',
      'bluetooth_auto_eq_desc':
          'Bluetooth cihazları için EQ\'yu otomatik ayarla',
      'siri_shortcuts': 'Siri Kısayolları',
      'siri_shortcuts_desc': 'Sesli komut kısayollarını yapılandır',
      'siri_integration': 'Siri Entegrasyonu',
      'siri_integration_desc': 'Siri komutlarıyla oynatmayı kontrol et',
      'custom_shortcuts': 'Özel Kısayollar',
      'custom_shortcuts_desc': 'Özel sesli komutlar oluştur',
      'siri_shortcuts_info':
          'Siri Kısayolları iOS Ayarları > Siri & Search bölümünden yönetilir',
      'voice_feedback': 'Sesli Geri Bildirim',
      'voice_feedback_desc': 'Parça değişimlerini ve durumunu duyur',
      'voice_control': 'Ses Kontrolü',
      'shared_links': 'Paylaşılan Bağlantılar',
      'no_audiobooks_found': 'Sesli kitap bulunamadı',
      'import_audiobooks_hint': 'Klasör içe aktararak başlayın',
      'local_results': 'Yerel Sonuçlar',
      'online_results': 'İnternet Sonuçları',
      'no_results': 'Sonuç bulunamadı',
      'playing_genre': '{genre} şarkıları çalınıyor',
      'no_genre_songs': 'Kitaplığınızda {genre} şarkısı yok',
      'mix_artist': 'Karışım: {artist}',
      'daily_mix': 'Günlük Karışım {number}',
      'airplay': 'AirPlay',
      'airplay_desc': 'Mevcut AirPlay cihazlarına aktar',
      'podcast': 'Podcast',
      'podcast_desc': 'Podcast aboneliklerini yönet',
      'audiobook': 'Sesli Kitap',
      'audiobook_desc': 'Sesli kitap kütüphanesine göz at',
      'widget': 'Widget',
      'widget_desc': 'Ana ekran widget\'larını yapılandır',
      // Splash
      'signal_path_preparing': 'Deneyiminiz hazırlanıyor...',
      'scanning_library': 'Kitaplık taranıyor...',
      'enjoy_listening': 'Keyifli dinlemeler!',
      'import_playlist': 'Çalma Listesi İçe Aktar',
      'import_playlist_hint':
          'Spotify, YouTube Music veya Deezer çalma listesi bağlantısını yapıştırın. Şarkılar eşleştirilir ve çevrim içi dinlenebilir/indirilebilir.',
      'playlist_name': 'Çalma Listesi Adı',
      'importing': 'İçe aktarılıyor...',
      'import': 'İçe Aktar',
      'playlist_imported': 'Çalma listesi içe aktarıldı.',
    },
    'de': {
      'home': 'Startseite',
      'library': 'Mediathek',
      'search': 'Suche',
      'settings': 'Einstellungen',
      'now_playing': 'Jetzt läuft',
      'no_song_playing': 'Kein Titel spielt',
      'no_music_playing': 'Keine Musik spielt',
      'your_music_awaits': 'Deine Musik wartet',
      'import_songs_to_start':
          'Importiere Songs von deinem Gerät, um zu beginnen',
      'import_music': 'Musik importieren',
      'liked_songs': 'Gefällt mir',
      'albums': 'Alben',
      'popular_artists': 'Beliebte Künstler',
      'playlists': 'Wiedergabelisten',
      'see_all': 'Alle anzeigen',
      'your_top_mixes': 'Deine Mixes',
      'recently_added': 'Kürzlich hinzugefügt',
      'songs': 'Titel',
      'artists': 'Künstler',
      'genres': 'Genres',
      'sort_by_title': 'Nach Titel sortieren',
      'sort_by_artist': 'Nach Künstler sortieren',
      'sort_by_album': 'Nach Album sortieren',
      'sort_by_duration': 'Nach Dauer sortieren',
      'sort_by_date_added': 'Nach Hinzufügungsdatum sortieren',
      'no_albums_found': 'Keine Alben gefunden',
      'no_artists_found': 'Keine Künstler gefunden',
      'no_genres_found': 'Keine Genres gefunden',
      'your_library_is_empty': 'Deine Mediathek ist leer',
      'import_music_from_device': 'Importiere Musik von deinem Gerät',
      'scan_music_library': 'Musikmediathek scannen',
      'what_to_listen': 'Was möchtest du hören?',
      'recent_searches': 'Letzte Suchanfragen',
      'clear': 'Löschen',
      'browse_all': 'Alle durchsuchen',
      'no_results_for': 'Keine Ergebnisse für',
      'queue': 'Warteschlange',
      'queue_is_empty': 'Warteschlange ist leer',
      'add_songs': 'Titel Hinzufügen',
      'all_songs_added': 'Alle Titel bereits hinzugefügt',
      'add_songs_to_start':
          'Füge Titel hinzu, um mit der Wiedergabe zu beginnen',
      'add_to_playlist': 'Zur Wiedergabeliste hinzufügen',
      'song_info': 'Titelinfo',
      'share': 'Teilen',
      'sleep_timer': 'Schlaftimer',
      'no_playlists_yet': 'Noch keine Wiedergabelisten. Erstelle zuerst eine.',
      'create_new_playlist': 'Neue Wiedergabeliste erstellen',
      'new_playlist': 'Neue Wiedergabeliste',
      'playlist_name': 'Name der Wiedergabeliste',
      'cancel': 'Abbrechen',
      'close': 'Schließen',
      'rename_playlist': 'Wiedergabeliste umbenennen',
      'delete_playlist': 'Wiedergabeliste löschen',
      'rename': 'Umbenennen',
      'delete': 'Löschen',
      'delete_playlist_warning': 'Bist du sicher, dass du löschen möchtest',
      'no_songs_in_playlist': 'Keine Titel in dieser Wiedergabeliste',
      'add_songs_from_library': 'Füge Titel aus der Mediathek hinzu',
      'play': 'Abspielen',
      'appearance': 'Erscheinungsbild',
      'theme': 'Design',
      'theme_mode': 'Design-Modus',
      'custom_colors': 'Benutzerdefinierte Farben',
      'dark': 'Dunkel',
      'light': 'Hell',
      'system': 'System',
      'language': 'Sprache',
      'app_language': 'App-Sprache',
      'music_library': 'Musikmediathek',
      'rescan_library': 'Mediathek neu scannen',
      'scan_device_for_music': 'Scanne Gerät nach neuer oder entfernter Musik',
      'import_from_files': 'Aus Dateien importieren',
      'browse_and_import': 'Durchsuche und importiere Audiodateien',
      'import_from_folder': 'Aus Ordner importieren',
      'scan_folder_for_music': 'Scanne einen bestimmten Ordner nach Musik',
      'storage': 'Speicher',
      'local_songs': 'Lokale Titel',
      'songs_in_library': 'Titel in der Mediathek',
      'clear_library': 'Mediathek leeren',
      'remove_cached_data': 'Alle zwischengespeicherten Musikdaten entfernen',
      'clear_library_title': 'Mediathek leeren',
      'clear_library_confirm':
          'Dadurch werden alle zwischengespeicherten Musikdaten entfernt. Deine eigentlichen Musikdateien werden nicht gelöscht.',
      'audio': 'Audio',
      'equalizer': 'Equalizer',
      'adjust_sound_frequencies': 'Klangfrequenzen anpassen',
      'equalizer_coming_soon': 'Equalizer kommt bald',
      'equalizer_not_available': 'Equalizer auf diesem Gerät nicht verfügbar',
      'accounts': 'Konten',
      'connected_as': 'Verbunden als',
      'disconnect': 'Trennen',
      'spotify': 'Spotify',
      'connect_spotify_description':
          'Importiere deine Spotify-Playlists und Lieblingssongs. Verbinde mit deinem Browser-Cookie.',
      'spotify_cookie_instructions':
          '1. Öffne open.spotify.com im Browser\n2. Melde dich an\n3. Öffne DevTools (F12) > Application > Cookies\n4. Kopiere den Wert von "sp_dc"\n5. Füge ihn unten ein',
      'paste_sp_dc_cookie': 'sp_dc-Cookie einfügen',
      'import_liked_songs': 'Lieblingssongs importieren',
      'spotify_connected_as': 'Verbunden als',
      'enter_spotify_username': 'Spotify-Benutzername (optional)',
      'connect_spotify': 'Spotify-Mediathek verbinden',
      'i_authorized': 'Autorisiert',
      'auth_failed_try_again':
          'Autorisierung fehlgeschlagen. Bitte versuche es erneut.',
      'presets': 'Voreinstellungen',
      'default_playback_speed': 'Standard-Wiedergabegeschwindigkeit',
      'volume_boost': 'Lautstärkeverstärkung',
      'playback': 'Wiedergabe',
      'auto_shuffle': 'Automatisch mischen',
      'automatically_shuffle': 'Automatisch mischen bei Wiedergabe',
      'gapless_playback': 'Nahtlose Wiedergabe',
      'seamless_transition': 'Nahtloser Übergang zwischen Titeln',
      'crossfade': 'Überblendung',
      'seconds_crossfade': 's Überblendung',
      'off': 'Aus',
      'apply': 'Anwenden',
      'about': 'Über',
      'version': 'Version',
      'built_with_flutter': 'Mit Flutter & Liebe entwickelt',
      'acknowledgments': 'Open-Source-Dank',
      'credits': 'Danksagungen',
      'open_source_licenses': 'Open-Source-Komponenten und Lizenzen',
      'developer': 'Entwickler',
      'repeat_all': 'Alle wiederholen',
      'repeat_one': 'Einzeln wiederholen',
      'shuffled': 'Zufallswiedergabe',
      'added_to': 'Hinzugefügt zu',
      'created_and_added_to': 'Erstellt und hinzugefügt zu',
      'no_songs': 'Keine Titel',
      'english': 'Englisch',
      'turkish': 'Türkisch',
      'german': 'Deutsch',
      'scan_media_library': 'Mediathek scannen',
      'import_from_apple_music': 'Aus Apple Music Mediathek importieren',
      'browse_files': 'Dateien durchsuchen',
      'select_audio_files': 'Audiodateien aus der Dateien-App auswählen',
      'import_from_folder_title': 'Aus Ordner importieren',
      'scan_specific_folder': 'Bestimmten Ordner scannen',
      'seconds': 'Sekunden',
      'melodi': 'Melodi',
      'add_to_queue': 'Zur Warteschlange hinzufügen',
      'play_next': 'Als Nächstes abspielen',
      'view_album': 'Album anzeigen',
      'view_artist': 'Künstler anzeigen',
      'watched_folder': 'Überwachter Ordner',
      'auto_scan_folder': 'Ordner bei jedem Start automatisch scannen',
      'watching': 'Überwacht',
      'folder_set': 'Ordner festgelegt',
      'could_not_open_link': 'Link konnte nicht geöffnet werden',
      'youtube_search_hint': 'Auf YouTube suchen',
      'downloading': 'Herunterladen...',
      'download_complete': 'Download abgeschlossen',
      'download_failed': 'Download fehlgeschlagen',
      'loading_song': 'Laden',
      'sleep_timer_canceled': 'Schlaftimer abgebrochen',
      'output_selection': 'Auswahl der Audioausgabe',
      'device_selection': 'Geräteauswahl',
      'artist_label': 'Künstler',
      'album_label': 'Album',
      'genre_label': 'Genre',
      'year_label': 'Jahr',
      'track_label': 'Titel',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Dauer',
      'file_label': 'Datei',
      'accent_color': 'Akzentfarbe',
      'tap_to_change': 'Zum Ändern tippen',
      'background': 'Hintergrund',
      'surface': 'Oberfläche',
      'card': 'Karte',
      'text_primary': 'Primärtext',
      'text_secondary': 'Sekundärtext',
      'reset_colors': 'Farben zurücksetzen',
      'default_color': 'Standard',
      'create_playlist': 'Playlist erstellen',
      'share_song': 'Song teilen',
      'share_file': 'Audiodatei teilen',
      'now_playing_queue': 'Wiedergabe aus Warteschlange',
      'song_count': 'Titel',
      'min': 'Min',
      'hr': 'Std',
      'dynamic_colors': 'Dynamische Farben',
      'apply_album_colors': 'Farben vom Albumcover übernehmen',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description':
          'Importiere deine YouTube Music Bibliothek. Verbinde mit deinem Browser-Cookie.',
      'ytmusic_cookie_instructions':
          '1. Gehe zu music.youtube.com im Browser\n2. Melde dich an\n3. Öffne DevTools (F12) > Application > Cookies\n4. Kopiere den Wert von "__Secure-3PSAPISID"\n5. Füge ihn unten ein',
      'paste_ytmusic_cookie': 'SAPISID-Cookie einfügen',
      'import_albums': 'Alben importieren',
      'connect_youtube_music': 'YouTube Music verbinden',
      'auto_sync': 'Auto-Sync',
      'sync_time': 'Sync-Zeit',
      'wifi_only': 'Nur WLAN',
      'sync_schedule': 'Sync-Plan',
      'online_mode': 'Online-Modus',
      'offline_mode': 'Offline-Modus',
      'stream_on_cellular': 'Streaming über Mobilfunk',
      'streaming': 'Streaming',
      'synced_lyrics': 'Synchronisierte Liedtexte',
      'no_lyrics': 'Keine Liedtexte verfügbar',
      'instrumental': 'Instrumental',
      'login_with_browser': 'Mit Browser anmelden',
      'cookie_paste': 'oder Cookie manuell einfügen',
      'like_mirroring': 'Like-Synchronisation',
      'mirror_likes': 'Likes synchronisieren',
      'mirroring_enabled': 'Synchronisation aktiv',
      'mirrored_count': 'Synchronisiert',
      'mirror_now': 'Jetzt synchronisieren',
      'last_mirrored': 'Letzte Synchronisation',
      'mirror_likes_description':
          'Likes zwischen Spotify und YouTube Music synchron halten',
      'mixes': 'Mixe',
      'release_radar': 'Release-Radar',
      'discover_weekly': 'Wöchentliche Entdeckungen',
      'regenerate': 'Neu generieren',
      'no_mixes_yet': 'Noch keine Mixe generiert',
      'generated_at': 'Generiert am',
      'diagnostics': 'Diagnose',
      'export_diagnostics': 'Exportieren',
      'clear_logs': 'Logs löschen',
      'error_logs': 'Fehlerprotokolle',
      'service_status': 'Dienststatus',
      'app_info': 'App-Info',
      'crash_reports': 'Absturzberichte',
      'scrobbling': 'Scrobbling',
      'yt_history_scrobbling': 'YouTube-Verlauf übertragen',
      'scrobble_now': 'Jetzt übertragen',
      'scrobbled_count': 'Übertragen',
      'scrobbling_enabled': 'Auto-Übertragung',
      'last_scrobbled': 'Letzte Übertragung',
      'recent_scrobbles': 'Letzte Übertragungen',
      'auth_expired': 'Verbindung abgelaufen',
      'reconnect': 'Erneut verbinden',
      'auth_expired_desc':
          'Ihre {service}-Verbindung ist abgelaufen. Tippen Sie zum erneuten Verbinden.',
      'streaming_prompt_title': 'Streaming-Modus',
      'streaming_prompt_body':
          'Dieser Titel benötigt Download. Stattdessen streamen?',
      'stream': 'Streamen',
      'download': 'Herunterladen',
      'download_all': 'Alle herunterladen',
      'download_queued': 'Zur Download-Warteschlange hinzugefügt',
      'download_already_queued':
          'Bereits heruntergeladen oder in der Download-Warteschlange.',
      'spotify_playlist_load_failed':
          'Die Spotify-Playlist konnte nicht geladen werden.',
      'playback_failed': 'Wiedergabe fehlgeschlagen',
      'more': 'Weitere Optionen',
      'wrong_match': 'Falscher Treffer?',
      'find_alternative': 'Alternative finden',
      'no_alternatives': 'Keine Alternativen gefunden',
      'album_discovery': 'Entdecken',
      'new_releases': 'Neuerscheinungen',
      'browse_genre': 'Nach Genre durchsuchen',
      'artist_profile': 'Künstler',
      'related_artists': 'Ähnliche Künstler',
      'discography': 'Diskografie',
      'play_all': 'Alle abspielen',
      'followers': 'Follower',
      'following': 'Folge ich',
      'follow': 'Folgen',
      'unfollow': 'Entfolgen',
      'save': 'Speichern',
      'sync_settings': 'Sync-Einstellungen',
      'sync_this_playlist': 'Diese Playlist synchronisieren',
      'sync_direction': 'Richtung',
      'spotify_to_yt': 'Spotify → YT Music',
      'yt_to_spotify': 'YT Music → Spotify',
      'bidirectional': 'Bidirektional',
      'sync_now': 'Jetzt synchronisieren',
      'last_synced': 'Zuletzt synchronisiert',
      'default_sync': 'Standard-Sync',
      'syncing_enabled': 'Synchronisierung',
      'metadata_backfill': 'Metadaten',
      'backfill_art': 'Albumcover nachtragen',
      'backfill_lyrics': 'Liedtexte nachtragen',
      'backfill_all': 'Alle nachtragen',
      'high_res_art': 'Hochauflösendes Cover',
      'lyrics': 'Liedtexte',
      'backfill_progress': 'Fortschritt',
      'last_backfilled': 'Zuletzt nachgetragen',
      'lossless': 'Verlustfrei',
      'lossless_quality': 'Verlustfreie Qualität',
      'embed_metadata': 'Metadaten einbetten',
      'cover_resolution': 'Cover-Auflösung',
      'high': 'Hoch',
      'medium': 'Mittel',
      'low': 'Niedrig',
      'loudness_norm': 'Lautstärke-Normalisierung',
      'downloads': 'Downloads',
      'active': 'Aktiv',
      'completed': 'Abgeschlossen',
      'failed': 'Fehlgeschlagen',
      'retry': 'Wiederholen',
      'retry_all': 'Alle wiederholen',
      'clear_all': 'Alle löschen',
      'no_downloads': 'Keine Downloads',
      'no_failed_downloads': 'Keine fehlgeschlagenen Downloads',
      'download_progress': 'Fortschritt',
      'download_location': 'Download-Pfad',
      'match_confidence': 'Treffergenauigkeit',
      'exact_match': 'Genauer Treffer',
      'fuzzy_match': 'Ähnlichkeitstreffer',
      'manual_match': 'Manueller Treffer',
      'rematch_all': 'Alle neu zuordnen',
      'match_progress': 'Zuordnung läuft',
      'resolving': 'Quelle wird aufgelöst...',
      'downloading_file': 'Wird heruntergeladen...',
      'embedding': 'Metadaten werden eingebettet...',
      'minutes': 'Min.',
      'timer_active': 'Timer aktiv',
      'cancel_timer': 'Timer abbrechen',
      'timer_ended': 'Wiedergabe pausiert',
      'reset_eq': 'Zurücksetzen',
      'normal': 'Normal',
      'pop': 'Pop',
      'rock': 'Rock',
      'jazz': 'Jazz',
      'classical': 'Klassik',
      'bass_boost': 'Bass Boost',
      'vocal': 'Gesang',
      'custom_eq': 'Benutzerdefiniert',
      'blocklist': 'Blockierte Titel',
      'block_track': 'Blockieren',
      'unblock': 'Entblocken',
      'no_blocked_tracks': 'Keine blockierten Titel',
      'no_shared_links': 'Noch keine geteilten Links',
      'blocked_count': 'Blockiert',
      'scheduled_sync': 'Geplante Synchronisierung',
      'sync_days': 'Sync-Tage',
      'next_sync': 'Nächste Sync',
      'run_sync_now': 'Jetzt sync.',
      'sync_enabled': 'Auto-Sync',
      'library_size': 'Bibliotheksgröße',
      'clear_cache': 'Cache leeren',
      'move_library': 'Bibliothek verschieben',
      'storage_location': 'Speicherort',
      'format_breakdown': 'Formatverteilung',
      'used_space': 'Belegt',
      'free_space': 'Frei',
      'monday': 'Mo',
      'tuesday': 'Di',
      'wednesday': 'Mi',
      'thursday': 'Do',
      'friday': 'Fr',
      'saturday': 'Sa',
      'sunday': 'So',
      'spotify_cookie_login': 'Cookie-Anmeldung',
      'sp_dc_label': 'sp_dc-Cookie',
      'sp_key_label': 'sp_key-Cookie',
      'yt_cookie_login': 'YouTube-Cookie-Anmeldung',
      'yt_cookie_label': 'Cookie-String',
      'cookie_auth_desc': 'Cookies aus Browser einfügen',
      'listening_stats': 'Hörstatistiken',
      'total_plays': 'Gesamte Wiedergaben',
      'total_listening_time': 'Hördauer',
      'unique_artists': 'Einzigartige Künstler',
      'audio_quality': 'Audioqualität',
      'streaming_quality': 'Streaming',
      'download_quality': 'Downloads',
      'cellular_quality': 'Mobil',
      'wifi_quality': 'WLAN',
      'quality_auto': 'Auto',
      'quality_low': 'Niedrig',
      'quality_normal': 'Normal',
      'quality_high': 'Hoch',
      'quality_lossless': 'Verlustfrei',
      'file_organization': 'Dateiorganisation',
      'organized_by_artist': 'Nach Künstler/Album',
      'flat_structure': 'Flach',
      'organize_now': 'Jetzt organisieren',
      'keep_downloads': 'Downloads behalten',
      'auto_delete': 'Auto-löschen nach',
      'never': 'Nie',
      'days': 'Tage',
      'storage_management': 'Speicherverwaltung',
      'preview': 'Vorschau',
      'library_health': 'Bibliotheksstatus',
      'health_score': 'Gesundheit',
      'scan_library': 'Bibliothek scannen',
      'rescan': 'Erneut scannen',
      'fix_all': 'Alle reparieren',
      'issues_found': 'Probleme gefunden',
      'no_issues': 'Bibliothek ist gesund!',
      'missing_art': 'Fehlendes Albumcover',
      'missing_metadata': 'Fehlende Metadaten',
      'failed_downloads_issue': 'Fehlgeschlagene Downloads',
      'low_confidence': 'Niedrige Treffergenauigkeit',
      'duplicates': 'Doppelte Titel',
      'orphaned_files': 'Verwaiste Dateien',
      'x_tracks_need_art': '{count} Titel benötigen Albumcover',
      'x_tracks_need_lyrics': '{count} Titel benötigen Liedtexte',
      'x_tracks_waiting_lossless': '{count} Titel warten auf verlustfrei',
      'x_downloads_failed': '{count} Downloads fehlgeschlagen',
      'stream_cache': 'Stream-Cache',
      'cache_size': 'Cache-Größe',
      'resume_playback': 'Wiedergabe fortsetzen',
      'cache_cleared': 'Cache geleert',
      'quick_access': 'SCHNELLZUGRIFF',
      'recently_played_subtitle': 'Zuletzt gespielte Titel',
      'liked_songs_subtitle': 'Deine Lieblingssongs',
      'downloads_subtitle': 'Heruntergeladene Titel',
      'scrobbling_subtitle': 'Hörverlauf',
      'listening_history': 'Hörverlauf',
      'calendar': 'Kalender',
      'statistics': 'Statistiken',
      'suggestions': 'Vorschläge',
      'no_listening_history': 'Kein Hörverlauf für dieses Datum',
      'top_tracks': 'Top-Titel',
      'top_artists': 'Top-Künstler',
      'time_based_suggestion': 'Zeitbasierte Vorschläge',
      'recent_favorites': 'Aktuelle Favoriten',
      'top_this_week': 'Top dieser Woche',
      'not_enough_data': 'Nicht genügend Daten für Vorschläge',
      'times': 'mal',
      'morning_suggestion': 'Morgenstimmung',
      'afternoon_suggestion': 'Nachmittagsenergie',
      'evening_suggestion': 'Abendstimmung',
      'night_suggestion': 'Nacht-Session',
      // Onboarding
      'welcome_to_melodi': 'Willkommen bei\nMelodi',
      'onboarding_welcome_desc':
          'Dein persönlicher Musikbegleiter.\nSchön, schnell und für dich gemacht.',
      'choose_language': 'Sprache\nwählen',
      'onboarding_language_desc':
          'Wähle deine bevorzugte Sprache.\nDu kannst dies später ändern.',
      'choose_theme': 'Design\nwählen',
      'onboarding_theme_desc':
          'Wähle ein Aussehen, das zu dir passt.\nDunkel oder hell — du entscheidest.',
      'connect_services': 'Dienste\nverbinden',
      'onboarding_services_desc':
          'Verbinde deine Streaming-Konten, um\nPlaylists zu importieren und deine Wiedergaben zu synchronisieren.',
      'get_started': 'Loslegen',
      'skip': 'Überspringen',
      'next': 'Weiter',
      'import_playlists': 'Playlists importieren',
      'import_songs': 'Musikbibliothek synchronisieren',
      'connect_for_scrobbling': 'Hörverlauf verfolgen',
      'spotify_subtitle': 'Playlists & Lieder importieren',
      'youtube_subtitle': 'Musikbibliothek synchronisieren',
      // Greetings
      'good_morning': 'Guten Morgen',
      'good_afternoon': 'Guten Tag',
      'good_evening': 'Guten Abend',
      'general': 'Allgemein',
      // Accent color names
      'color_spotify_green': 'Spotify Grün',
      'color_green': 'Grün',
      'color_red': 'Rot',
      'color_pink': 'Rosa',
      'color_blue': 'Blau',
      'color_indigo': 'Indigo',
      'color_purple': 'Lila',
      'color_orange': 'Orange',
      'color_yellow': 'Gelb',
      'color_mint': 'Minze',
      'color_teal': 'Türkis',
      'color_white': 'Weiß',
      'color_rose': 'Rosen',
      'color_deep_purple': 'Dunkles Lila',
      'color_light_blue': 'Hellblau',
      'color_cyan': 'Cyan',
      'color_material_green': 'Material Grün',
      'color_deep_orange': 'Dunkles Orange',
      'color_brown': 'Braun',
      'color_blue_grey': 'Blaugrau',
      // Equalizer presets
      'preset_flat': 'Flach',
      'preset_classical': 'Klassik',
      'preset_dance': 'Tanz',
      'preset_acoustic': 'Akustik',
      'preset_bass_boost': 'Bass Boost',
      'preset_treble_boost': 'Höhen Boost',
      'preset_loudness': 'Lautstärke',
      'preset_rock': 'Rock',
      'preset_pop': 'Pop',
      'preset_jazz': 'Jazz',
      'preset_voice': 'Stimme',
      'preset_custom': 'Benutzerdefiniert',
      // Library
      'liked_songs_label': 'Lieder',
      'recently_played': 'Zuletzt gespielt',
      'sort_by_recent': 'Nach zuletzt gespielt',
      'sort_by_name': 'Nach Name',
      'sort_by_date': 'Nach Datum',
      'playlist_count': 'Playlist • {count} Titel',
      'artist_count': 'Künstler • {count} Titel',
      'album_count': 'Album • {count}',
      // Create playlist
      'create': 'Erstellen',
      'create_playlist_button': 'Playlist erstellen',
      'add_cover_photo': 'Coverfoto hinzufügen',
      'enter_playlist_name': 'Playlist-Name eingeben',
      'description': 'Beschreibung',
      'optional_description': 'Optionale Beschreibung',
      'privacy': 'Privatsphäre',
      'private_playlist': 'Private Playlist',
      'high_fidelity_active': 'HiFi-Erfahrung aktiv',
      // Audio settings
      'audio_effects': 'Audioeffekte',
      'audio_effects_desc': 'Raumklang, Hall, Bass-Boost',
      'eq_presets': 'EQ-Voreinstellungen',
      'eq_presets_desc': 'Wähle aus voreingestellten Equalizer-Profilen',
      'gapless_playback_setting': 'Nahtlose Wiedergabe',
      'gapless_playback_desc': 'Nahtloser Übergang zwischen Titeln',
      'bluetooth_auto_eq': 'Bluetooth Auto-EQ',
      'bluetooth_auto_eq_desc': 'EQ automatisch für Bluetooth-Geräte anpassen',
      'siri_shortcuts': 'Siri-Tastenkombinationen',
      'siri_shortcuts_desc': 'Sprachsteuerung konfigurieren',
      'siri_integration': 'Siri-Integration',
      'siri_integration_desc': 'Wiedergabe mit Siri-Befehlen steuern',
      'custom_shortcuts': 'Benutzerdefinierte Tastenkombinationen',
      'custom_shortcuts_desc': 'Erstelle benutzerdefinierte Sprachbefehle',
      'siri_shortcuts_info':
          'Siri-Tastenkombinationen werden in iOS-Einstellungen > Siri & Suchen verwaltet',
      'voice_feedback': 'Sprachfeedback',
      'voice_feedback_desc': 'Titeländerungen und Status ansagen',
      'voice_control': 'Sprachsteuerung',
      'shared_links': 'Geteilte Links',
      'no_audiobooks_found': 'Keine Hörbücher gefunden',
      'import_audiobooks_hint': 'Importiere aus einem Ordner um zu beginnen',
      'local_results': 'Lokale Ergebnisse',
      'online_results': 'Online-Ergebnisse',
      'no_results': 'Keine Ergebnisse gefunden',
      'playing_genre': '{genre}-Titel werden abgespielt',
      'no_genre_songs': 'Keine {genre}-Titel in deiner Bibliothek',
      'mix_artist': 'Mix: {artist}',
      'daily_mix': 'Tägliches Mix {number}',
      'airplay': 'AirPlay',
      'airplay_desc': 'Auf verfügbare AirPlay-Geräte streamen',
      'podcast': 'Podcast',
      'podcast_desc': 'Podcast-Abonnements verwalten',
      'audiobook': 'Hörbuch',
      'audiobook_desc': 'Hörbuchbibliothek durchsuchen',
      'widget': 'Widget',
      'widget_desc': 'Home-Screen-Widgets konfigurieren',
      // Splash
      'signal_path_preparing': 'Dein Erlebnis wird vorbereitet...',
      'scanning_library': 'Bibliothek wird gescannt...',
      'enjoy_listening': 'Viel Spaß beim Hören!',
      'import_playlist': 'Playlist importieren',
      'import_playlist_hint':
          'Füge einen Spotify-, YouTube-Music- oder Deezer-Playlist-Link ein. Titel werden abgeglichen und können online gestreamt/heruntergeladen werden.',
      'playlist_name': 'Playlist-Name',
      'importing': 'Wird importiert...',
      'import': 'Importieren',
      'playlist_imported': 'Playlist importiert.',
    },
  };

  static String tr(String key) {
    final map = _strings[currentLocale] ?? _strings['en']!;
    return map[key] ?? _strings['en']![key] ?? key;
  }
}

extension AppLocaleExtension on BuildContext {
  String tr(String key) => AppLocale.tr(key);
}
