import 'package:flutter/material.dart';

class LocaleNotifier extends ChangeNotifier {
  String _locale = 'tr';
  String get locale => _locale;

  void change(String locale) {
    _locale = locale;
    AppLocale.currentLocale = locale;
    notifyListeners();
  }
}

class AppLocale {
  static String currentLocale = 'tr';

  static bool get isEnglish => currentLocale == 'en';
  static bool get isTurkish => currentLocale == 'tr';
  static bool get isGerman => currentLocale == 'de';

  static void change(String locale) {
    currentLocale = locale;
  }

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'home': 'Home',
      'library': 'Library',
      'search': 'Search',
      'settings': 'Settings',
      'now_playing': 'Now Playing',
      'no_song_playing': 'No song playing',
      'no_music_playing': 'No music playing',
      'your_music_awaits': 'Your music awaits',
      'import_songs_to_start': 'Import songs from your device to get started',
      'import_music': 'Import Music',
      'recently_played': 'Recently Played',
      'liked_songs': 'Liked Songs',
      'albums': 'Albums',
      'popular_artists': 'Popular Artists',
      'playlists': 'Playlists',
      'see_all': 'See All',
      'songs': 'Songs',
      'artists': 'Artists',
      'genres': 'Genres',
      'sort_by_title': 'Sort by Title',
      'sort_by_artist': 'Sort by Artist',
      'sort_by_album': 'Sort by Album',
      'sort_by_duration': 'Sort by Duration',
      'sort_by_date_added': 'Sort by Date Added',
      'no_albums_found': 'No albums found',
      'no_artists_found': 'No artists found',
      'no_genres_found': 'No genres found',
      'your_library_is_empty': 'Your library is empty',
      'import_music_from_device': 'Import music from your device',
      'scan_music_library': 'Scan Music Library',
      'what_to_listen': 'What do you want to listen to?',
      'recent_searches': 'Recent Searches',
      'clear': 'Clear',
      'browse_all': 'Browse All',
      'no_results_for': 'No results for',
      'queue': 'Queue',
      'queue_is_empty': 'Queue is empty',
      'add_songs': 'Add Songs',
      'all_songs_added': 'All songs already added',
      'add_songs_to_start': 'Add songs to start playing',
      'add_to_playlist': 'Add to Playlist',
      'song_info': 'Song Info',
      'share': 'Share',
      'sleep_timer': 'Sleep Timer',
      'no_playlists_yet': 'No playlists yet. Create one first.',
      'create_new_playlist': 'Create New Playlist',
      'new_playlist': 'New Playlist',
      'playlist_name': 'Playlist name',
      'cancel': 'Cancel',
      'create': 'Create',
      'rename_playlist': 'Rename Playlist',
      'delete_playlist': 'Delete Playlist',
      'rename': 'Rename',
      'delete': 'Delete',
      'delete_playlist_warning': 'Are you sure you want to delete',
      'no_songs_in_playlist': 'No songs in this playlist',
      'add_songs_from_library': 'Add songs from the library',
      'play': 'Play',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'theme_mode': 'Theme Mode',
      'custom_colors': 'Custom Colors',
      'dark': 'Dark',
      'light': 'Light',
      'system': 'System',
      'language': 'Language',
      'app_language': 'App Language',
      'music_library': 'Music Library',
      'rescan_library': 'Rescan Library',
      'scan_device_for_music': 'Scan device for new or removed music',
      'import_from_files': 'Import from Files',
      'browse_and_import': 'Browse and import audio files',
      'import_from_folder': 'Import from Folder',
      'scan_folder_for_music': 'Scan a specific folder for music',
      'storage': 'Storage',
      'local_songs': 'Local Songs',
      'songs_in_library': 'songs in library',
      'clear_library': 'Clear Library',
      'remove_cached_data': 'Remove all cached music data',
      'clear_library_title': 'Clear Library',
      'clear_library_confirm': 'This will remove all cached music data. Your actual music files will not be deleted.',
      'audio': 'Audio',
      'equalizer': 'Equalizer',
      'adjust_sound_frequencies': 'Adjust sound frequencies',
      'equalizer_coming_soon': 'Equalizer coming soon',
      'equalizer_not_available': 'Equalizer not available on this device',
      'accounts': 'Accounts',
      'connected_as': 'Connected as',
      'disconnect': 'Disconnect',
      'connect_for_scrobbling': 'Connect for scrobbling',
      'spotify': 'Spotify',
      'connect_spotify_description': 'Import your Spotify playlists and liked songs. Connect with your browser cookie.',
      'spotify_cookie_instructions': '1. Go to open.spotify.com in a browser\n2. Log in\n3. Open DevTools (F12) > Application > Cookies\n4. Copy the value of "sp_dc"\n5. Paste it below',
      'paste_sp_dc_cookie': 'Paste sp_dc cookie',
      'import_playlists': 'Import Playlists',
      'import_liked_songs': 'Import Liked Songs',
      'spotify_connected_as': 'Connected as',
      'enter_spotify_username': 'Spotify username (optional)',
      'connect_spotify': 'Connect Spotify library',
      'connect_youtube_music': 'Connect YouTube Music',
      'lastfm_description': 'Scrobble your plays to Last.fm automatically. Connect your Last.fm account to track your listening history.',
      'connect_lastfm': 'Connect Last.fm',
      'authorize_lastfm': 'Authorize Last.fm',
      'lastfm_auth_instructions': '1. Tap the button below to open last.fm\n2. Log in and click "Yes, allow access"\n3. Come back and tap "I authorized"',
      'i_authorized': 'I Authorized',
      'auth_failed_try_again': 'Authorization failed. Please try again.',
      'scrobbling_enabled': 'Scrobbling is enabled',
      'presets': 'Presets',
      'default_playback_speed': 'Default Playback Speed',
      'volume_boost': 'Volume Boost',
      'playback': 'Playback',
      'auto_shuffle': 'Auto Shuffle',
      'automatically_shuffle': 'Automatically shuffle when playing',
      'gapless_playback': 'Gapless Playback',
      'seamless_transition': 'Seamless transition between songs',
      'crossfade': 'Crossfade',
      'seconds_crossfade': 's crossfade',
      'off': 'Off',
      'apply': 'Apply',
      'about': 'About',
      'version': 'Version',
      'built_with_flutter': 'Built with Flutter & Love',
      'credits': 'Credits',
      'open_source_licenses': 'Open source components & licenses',
      'developer': 'Developer',
      'repeat_all': 'Repeat All',
      'repeat_one': 'Repeat One',
      'shuffled': 'Shuffled',
      'added_to': 'Added to',
      'created_and_added_to': 'Created and added to',
      'no_songs': 'No songs',
      'english': 'English',
      'turkish': 'Turkish',
      'german': 'German',
      'scan_media_library': 'Scan Media Library',
      'import_from_apple_music': 'Import from Apple Music library',
      'browse_files': 'Browse Files',
      'select_audio_files': 'Select audio files from Files app',
      'import_from_folder_title': 'Import from Folder',
      'scan_specific_folder': 'Scan a specific folder',
      'seconds': 'seconds',
      'melodi': 'Melodi',
      'add_to_queue': 'Add to Queue',
      'play_next': 'Play Next',
      'view_album': 'View Album',
      'view_artist': 'View Artist',
      'watched_folder': 'Watched Folder',
      'auto_scan_folder': 'Auto-scan a folder on every launch',
      'watching': 'Watching',
      'folder_set': 'Folder set',
      'could_not_open_link': 'Could not open link',
      'youtube_search_hint': 'Search on YouTube',
      'downloading': 'Downloading...',
      'download_complete': 'Download complete',
      'download_failed': 'Download failed',
      'loading_song': 'Loading',
      'sleep_timer_canceled': 'Sleep timer canceled',
      'output_selection': 'Output selection coming soon',
      'device_selection': 'Device selection coming soon',
      'artist_label': 'Artist',
      'album_label': 'Album',
      'genre_label': 'Genre',
      'year_label': 'Year',
      'track_label': 'Track',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Duration',
      'file_label': 'File',
      'accent_color': 'Accent Color',
      'tap_to_change': 'Tap to change',
      'background': 'Background',
      'surface': 'Surface',
      'card': 'Card',
      'text_primary': 'Text Primary',
      'text_secondary': 'Text Secondary',
      'reset_colors': 'Reset Colors',
      'default_color': 'Default',
      'create_playlist': 'Create Playlist',
      'share_song': 'Share Song',
      'share_file': 'Share Audio File',
      'now_playing_queue': 'Playing from Queue',
      'song_count': 'songs',
      'min': 'min',
      'hr': 'hr',
      'dynamic_colors': 'Dynamic Colors',
      'apply_album_colors': 'Apply colors from album art',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description': 'Import your YouTube Music library. Connect with your browser cookie.',
      'ytmusic_cookie_instructions': '1. Go to music.youtube.com in a browser\n2. Log in\n3. Open DevTools (F12) > Application > Cookies\n4. Copy the value of "__Secure-3PSAPISID"\n5. Paste it below',
      'paste_ytmusic_cookie': 'Paste SAPISID cookie',
      'import_songs': 'Import Songs',
      'import_albums': 'Import Albums',
      'connect_youtube_music': 'Connect YouTube Music',
      'auto_sync': 'Auto Sync',
      'sync_time': 'Sync Time',
      'wifi_only': 'Wi-Fi Only',
      'sync_schedule': 'Sync Schedule',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'stream_on_cellular': 'Stream on Cellular',
      'streaming': 'Streaming',
      'synced_lyrics': 'Synced Lyrics',
      'no_lyrics': 'No lyrics available',
      'instrumental': 'Instrumental',
    },
    'tr': {
      'home': 'Ana Sayfa',
      'library': 'Kitaplık',
      'search': 'Ara',
      'settings': 'Ayarlar',
      'now_playing': 'Şimdi Çalıyor',
      'no_song_playing': 'Şarkı çalmıyor',
      'no_music_playing': 'Müzik çalmıyor',
      'your_music_awaits': 'Müziğiniz sizi bekliyor',
      'import_songs_to_start': 'Başlamak için cihazınızdan şarkı içe aktarın',
      'import_music': 'Müzik İçe Aktar',
      'recently_played': 'Son Çalınanlar',
      'liked_songs': 'Beğenilen Şarkılar',
      'albums': 'Albümler',
      'popular_artists': 'Popüler Sanatçılar',
      'playlists': 'Çalma Listeleri',
      'see_all': 'Tümünü Gör',
      'songs': 'Şarkılar',
      'artists': 'Sanatçılar',
      'genres': 'Türler',
      'sort_by_title': 'Başlığa Göre Sırala',
      'sort_by_artist': 'Sanatçıya Göre Sırala',
      'sort_by_album': 'Albüme Göre Sırala',
      'sort_by_duration': 'Süreye Göre Sırala',
      'sort_by_date_added': 'Eklenme Tarihine Göre Sırala',
      'no_albums_found': 'Albüm bulunamadı',
      'no_artists_found': 'Sanatçı bulunamadı',
      'no_genres_found': 'Tür bulunamadı',
      'your_library_is_empty': 'Kitaplığınız boş',
      'import_music_from_device': 'Cihazınızdan müzik içe aktarın',
      'scan_music_library': 'Müzik Kitaplığını Tara',
      'what_to_listen': 'Ne dinlemek istersiniz?',
      'recent_searches': 'Son Aramalar',
      'clear': 'Temizle',
      'browse_all': 'Tümünü Keşfet',
      'no_results_for': 'için sonuç bulunamadı',
      'queue': 'Sıra',
      'queue_is_empty': 'Sıra boş',
      'add_songs': 'Şarkı Ekle',
      'all_songs_added': 'Tüm şarkılar zaten eklendi',
      'add_songs_to_start': 'Çalmaya başlamak için şarkı ekleyin',
      'add_to_playlist': 'Çalma Listesine Ekle',
      'song_info': 'Şarkı Bilgisi',
      'share': 'Paylaş',
      'sleep_timer': 'Uyku Zamanlayıcı',
      'no_playlists_yet': 'Henüz çalma listeniz yok. Önce bir tane oluşturun.',
      'create_new_playlist': 'Yeni Çalma Listesi Oluştur',
      'new_playlist': 'Yeni Çalma Listesi',
      'playlist_name': 'Çalma listesi adı',
      'cancel': 'İptal',
      'create': 'Oluştur',
      'rename_playlist': 'Çalma Listesini Yeniden Adlandır',
      'delete_playlist': 'Çalma Listesini Sil',
      'rename': 'Yeniden Adlandır',
      'delete': 'Sil',
      'delete_playlist_warning': 'Silmek istediğinize emin misiniz',
      'no_songs_in_playlist': 'Bu çalma listesinde şarkı yok',
      'add_songs_from_library': 'Kitaplıktan şarkı ekleyin',
      'play': 'Oynat',
      'appearance': 'Görünüm',
      'theme': 'Tema',
      'theme_mode': 'Tema Modu',
      'custom_colors': 'Özel Renkler',
      'dark': 'Koyu',
      'light': 'Açık',
      'system': 'Sistem',
      'language': 'Dil',
      'app_language': 'Uygulama Dili',
      'music_library': 'Müzik Kitaplığı',
      'rescan_library': 'Kitaplığı Yeniden Tara',
      'scan_device_for_music': 'Yeni veya kaldırılan müzikler için cihazı tara',
      'import_from_files': 'Dosyalardan İçe Aktar',
      'browse_and_import': 'Ses dosyalarına göz atın ve içe aktarın',
      'import_from_folder': 'Klasörden İçe Aktar',
      'scan_folder_for_music': 'Müzik için belirli bir klasörü tara',
      'storage': 'Depolama',
      'local_songs': 'Yerel Şarkılar',
      'songs_in_library': 'kitaplıkta şarkı',
      'clear_library': 'Kitaplığı Temizle',
      'remove_cached_data': 'Tüm önbelleğe alınmış müzik verilerini kaldır',
      'clear_library_title': 'Kitaplığı Temizle',
      'clear_library_confirm': 'Bu, tüm önbelleğe alınmış müzik verilerini kaldıracaktır. Gerçek müzik dosyalarınız silinmeyecektir.',
      'audio': 'Ses',
      'equalizer': 'Ekolayzır',
      'adjust_sound_frequencies': 'Ses frekanslarını ayarlayın',
      'equalizer_coming_soon': 'Ekolayzır çok yakında',
      'equalizer_not_available': 'Ekolayzır bu cihazda mevcut değil',
      'accounts': 'Hesaplar',
      'connected_as': 'Bağlı:',
      'disconnect': 'Bağlantıyı Kes',
      'connect_for_scrobbling': 'Scrobbling için bağlanın',
      'spotify': 'Spotify',
      'connect_spotify_description': 'Spotify çalma listelerini ve beğenilen şarkılarını içe aktar. Tarayıcı çerezinle bağlan.',
      'spotify_cookie_instructions': '1. Tarayıcıda open.spotify.com\'a gidin\n2. Giriş yapın\n3. DevTools (F12) > Application > Cookies bölümünü açın\n4. "sp_dc" değerini kopyalayın\n5. Aşağıya yapıştırın',
      'paste_sp_dc_cookie': 'sp_dc çerezini yapıştır',
      'import_playlists': 'Çalma Listelerini İçe Aktar',
      'import_liked_songs': 'Beğenilen Şarkıları İçe Aktar',
      'spotify_connected_as': 'Bağlandı:',
      'enter_spotify_username': 'Spotify kullanıcı adı (isteğe bağlı)',
      'connect_spotify': 'Spotify kitaplığını bağla',
      'connect_youtube_music': 'YouTube Music bağla',
      'lastfm_description': 'Çaldıklarınızı otomatik olarak Last.fm\'e gönderin. Dinleme geçmişinizi takip etmek için Last.fm hesabınızı bağlayın.',
      'connect_lastfm': 'Last.fm\'e Bağlan',
      'authorize_lastfm': 'Last.fm\'i Yetkilendir',
      'lastfm_auth_instructions': '1. Aşağıdaki butona tıklayarak last.fm\'i açın\n2. Giriş yapın ve "Yes, allow access" deyin\n3. Geri gelin ve "Yetkilendirdim" deyin',
      'i_authorized': 'Yetkilendirdim',
      'auth_failed_try_again': 'Yetkilendirme başarısız. Lütfen tekrar deneyin.',
      'scrobbling_enabled': 'Scrobbling etkin',
      'presets': 'Ön Ayarlar',
      'default_playback_speed': 'Varsayılan Oynatma Hızı',
      'volume_boost': 'Ses Güçlendirme',
      'playback': 'Oynatma',
      'auto_shuffle': 'Otomatik Karıştır',
      'automatically_shuffle': 'Çalarken otomatik olarak karıştır',
      'gapless_playback': 'Kesintisiz Oynatma',
      'seamless_transition': 'Şarkılar arasında kesintisiz geçiş',
      'crossfade': 'Çapraz Geçiş',
      'seconds_crossfade': 'sn çapraz geçiş',
      'off': 'Kapalı',
      'apply': 'Uygula',
      'about': 'Hakkında',
      'version': 'Sürüm',
      'built_with_flutter': 'Flutter ve Sevgiyle Yapıldı',
      'credits': 'Katkıda Bulunanlar',
      'open_source_licenses': 'Açık kaynak bileşenler ve lisanslar',
      'developer': 'Geliştirici',
      'repeat_all': 'Tümünü Tekrarla',
      'repeat_one': 'Birini Tekrarla',
      'shuffled': 'Karıştır',
      'added_to': 'eklendi',
      'created_and_added_to': 'Oluşturuldu ve eklendi',
      'no_songs': 'Şarkı yok',
      'english': 'İngilizce',
      'turkish': 'Türkçe',
      'german': 'Almanca',
      'scan_media_library': 'Medya Kitaplığını Tara',
      'import_from_apple_music': 'Apple Music kitaplığından içe aktar',
      'browse_files': 'Dosyalara Göz At',
      'select_audio_files': 'Dosyalar uygulamasından ses dosyaları seçin',
      'import_from_folder_title': 'Klasörden İçe Aktar',
      'scan_specific_folder': 'Belirli bir klasörü tara',
      'seconds': 'saniye',
      'melodi': 'Melodi',
      'add_to_queue': 'Sıraya Ekle',
      'play_next': 'Sıradaki',
      'view_album': 'Albümü Gör',
      'view_artist': 'Sanatçıyı Gör',
      'watched_folder': 'İzlenen Klasör',
      'auto_scan_folder': 'Her açılışta bir klasörü otomatik tara',
      'watching': 'İzleniyor',
      'folder_set': 'Klasör ayarlandı',
      'could_not_open_link': 'Link açılamadı',
      'youtube_search_hint': 'YouTube\'da ara',
      'downloading': 'İndiriliyor...',
      'download_complete': 'İndirme tamamlandı',
      'download_failed': 'İndirme başarısız',
      'loading_song': 'Yükleniyor',
      'sleep_timer_canceled': 'Uyku zamanlayıcı kapatıldı',
      'output_selection': 'Ses çıkışı seçimi yakında',
      'device_selection': 'Cihaz seçimi yakında',
      'artist_label': 'Sanatçı',
      'album_label': 'Albüm',
      'genre_label': 'Tür',
      'year_label': 'Yıl',
      'track_label': 'Parça',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Süre',
      'file_label': 'Dosya',
      'accent_color': 'Vurgu Rengi',
      'tap_to_change': 'Değiştirmek için dokunun',
      'background': 'Arka Plan',
      'surface': 'Yüzey',
      'card': 'Kart',
      'text_primary': 'Birincil Metin',
      'text_secondary': 'İkincil Metin',
      'reset_colors': 'Renkleri Sıfırla',
      'default_color': 'Varsayılan',
      'create_playlist': 'Çalma Listesi Oluştur',
      'share_song': 'Şarkıyı Paylaş',
      'share_file': 'Ses Dosyasını Paylaş',
      'now_playing_queue': 'Sıradan Çalıyor',
      'song_count': 'şarkı',
      'min': 'dk',
      'hr': 'sa',
      'dynamic_colors': 'Dinamik Renkler',
      'apply_album_colors': 'Albüm kapağından renkleri uygula',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description': 'YouTube Music kitaplığınızı içe aktarın. Tarayıcı çerezinizle bağlanın.',
      'ytmusic_cookie_instructions': '1. Tarayıcıda music.youtube.com adresine gidin\n2. Giriş yapın\n3. Geliştirici Araçları (F12) > Application > Cookies bölümünü açın\n4. "__Secure-3PSAPISID" değerini kopyalayın\n5. Aşağıya yapıştırın',
      'paste_ytmusic_cookie': 'SAPISID çerezini yapıştır',
      'import_songs': 'Şarkıları İçe Aktar',
      'import_albums': 'Albümleri İçe Aktar',
      'connect_youtube_music': 'YouTube Music bağla',
      'auto_sync': 'Otomatik Senkronizasyon',
      'sync_time': 'Senkronizasyon Zamanı',
      'wifi_only': 'Sadece Wi-Fi',
      'sync_schedule': 'Senkronizasyon Takvimi',
      'online_mode': 'Çevrimiçi Mod',
      'offline_mode': 'Çevrimdışı Mod',
      'stream_on_cellular': 'Mobil Veride Akış',
      'streaming': 'Akış',
      'synced_lyrics': 'Senkronize Şarkı Sözleri',
      'no_lyrics': 'Şarkı sözü yok',
      'instrumental': 'Enstrümantal',
    },
    'de': {
      'home': 'Startseite',
      'library': 'Mediathek',
      'search': 'Suche',
      'settings': 'Einstellungen',
      'now_playing': 'Jetzt läuft',
      'no_song_playing': 'Kein Titel spielt',
      'no_music_playing': 'Keine Musik spielt',
      'your_music_awaits': 'Deine Musik wartet',
      'import_songs_to_start': 'Importiere Songs von deinem Gerät, um zu beginnen',
      'import_music': 'Musik importieren',
      'recently_played': 'Zuletzt gespielt',
      'liked_songs': 'Gefällt mir',
      'albums': 'Alben',
      'popular_artists': 'Beliebte Künstler',
      'playlists': 'Wiedergabelisten',
      'see_all': 'Alle anzeigen',
      'songs': 'Titel',
      'artists': 'Künstler',
      'genres': 'Genres',
      'sort_by_title': 'Nach Titel sortieren',
      'sort_by_artist': 'Nach Künstler sortieren',
      'sort_by_album': 'Nach Album sortieren',
      'sort_by_duration': 'Nach Dauer sortieren',
      'sort_by_date_added': 'Nach Hinzufügungsdatum sortieren',
      'no_albums_found': 'Keine Alben gefunden',
      'no_artists_found': 'Keine Künstler gefunden',
      'no_genres_found': 'Keine Genres gefunden',
      'your_library_is_empty': 'Deine Mediathek ist leer',
      'import_music_from_device': 'Importiere Musik von deinem Gerät',
      'scan_music_library': 'Musikmediathek scannen',
      'what_to_listen': 'Was möchtest du hören?',
      'recent_searches': 'Letzte Suchanfragen',
      'clear': 'Löschen',
      'browse_all': 'Alle durchsuchen',
      'no_results_for': 'Keine Ergebnisse für',
      'queue': 'Warteschlange',
      'queue_is_empty': 'Warteschlange ist leer',
      'add_songs': 'Titel Hinzufügen',
      'all_songs_added': 'Alle Titel bereits hinzugefügt',
      'add_songs_to_start': 'Füge Titel hinzu, um mit der Wiedergabe zu beginnen',
      'add_to_playlist': 'Zur Wiedergabeliste hinzufügen',
      'song_info': 'Titelinfo',
      'share': 'Teilen',
      'sleep_timer': 'Schlaftimer',
      'no_playlists_yet': 'Noch keine Wiedergabelisten. Erstelle zuerst eine.',
      'create_new_playlist': 'Neue Wiedergabeliste erstellen',
      'new_playlist': 'Neue Wiedergabeliste',
      'playlist_name': 'Name der Wiedergabeliste',
      'cancel': 'Abbrechen',
      'create': 'Erstellen',
      'rename_playlist': 'Wiedergabeliste umbenennen',
      'delete_playlist': 'Wiedergabeliste löschen',
      'rename': 'Umbenennen',
      'delete': 'Löschen',
      'delete_playlist_warning': 'Bist du sicher, dass du löschen möchtest',
      'no_songs_in_playlist': 'Keine Titel in dieser Wiedergabeliste',
      'add_songs_from_library': 'Füge Titel aus der Mediathek hinzu',
      'play': 'Abspielen',
      'appearance': 'Erscheinungsbild',
      'theme': 'Design',
      'theme_mode': 'Design-Modus',
      'custom_colors': 'Benutzerdefinierte Farben',
      'dark': 'Dunkel',
      'light': 'Hell',
      'system': 'System',
      'language': 'Sprache',
      'app_language': 'App-Sprache',
      'music_library': 'Musikmediathek',
      'rescan_library': 'Mediathek neu scannen',
      'scan_device_for_music': 'Scanne Gerät nach neuer oder entfernter Musik',
      'import_from_files': 'Aus Dateien importieren',
      'browse_and_import': 'Durchsuche und importiere Audiodateien',
      'import_from_folder': 'Aus Ordner importieren',
      'scan_folder_for_music': 'Scanne einen bestimmten Ordner nach Musik',
      'storage': 'Speicher',
      'local_songs': 'Lokale Titel',
      'songs_in_library': 'Titel in der Mediathek',
      'clear_library': 'Mediathek leeren',
      'remove_cached_data': 'Alle zwischengespeicherten Musikdaten entfernen',
      'clear_library_title': 'Mediathek leeren',
      'clear_library_confirm': 'Dadurch werden alle zwischengespeicherten Musikdaten entfernt. Deine eigentlichen Musikdateien werden nicht gelöscht.',
      'audio': 'Audio',
      'equalizer': 'Equalizer',
      'adjust_sound_frequencies': 'Klangfrequenzen anpassen',
      'equalizer_coming_soon': 'Equalizer kommt bald',
      'equalizer_not_available': 'Equalizer auf diesem Gerät nicht verfügbar',
      'accounts': 'Konten',
      'connected_as': 'Verbunden als',
      'disconnect': 'Trennen',
      'connect_for_scrobbling': 'Für Scrobbling verbinden',
      'spotify': 'Spotify',
      'connect_spotify_description': 'Importiere deine Spotify-Playlists und Lieblingssongs. Verbinde mit deinem Browser-Cookie.',
      'spotify_cookie_instructions': '1. Öffne open.spotify.com im Browser\n2. Melde dich an\n3. Öffne DevTools (F12) > Application > Cookies\n4. Kopiere den Wert von "sp_dc"\n5. Füge ihn unten ein',
      'paste_sp_dc_cookie': 'sp_dc-Cookie einfügen',
      'import_playlists': 'Playlists importieren',
      'import_liked_songs': 'Lieblingssongs importieren',
      'spotify_connected_as': 'Verbunden als',
      'enter_spotify_username': 'Spotify-Benutzername (optional)',
      'connect_spotify': 'Spotify-Mediathek verbinden',
      'connect_youtube_music': 'YouTube Music verbinden',
      'lastfm_description': 'Sende deine Plays automatisch an Last.fm. Verbinde dein Last.fm-Konto, um deinen Hörverlauf zu verfolgen.',
      'connect_lastfm': 'Mit Last.fm verbinden',
      'authorize_lastfm': 'Last.fm autorisieren',
      'lastfm_auth_instructions': '1. Öffne last.fm mit dem Button unten\n2. Melde dich an und klicke "Yes, allow access"\n3. Komm zurück und tippe auf "Autorisiert"',
      'i_authorized': 'Autorisiert',
      'auth_failed_try_again': 'Autorisierung fehlgeschlagen. Bitte versuche es erneut.',
      'scrobbling_enabled': 'Scrobbling ist aktiviert',
      'presets': 'Voreinstellungen',
      'default_playback_speed': 'Standard-Wiedergabegeschwindigkeit',
      'volume_boost': 'Lautstärkeverstärkung',
      'playback': 'Wiedergabe',
      'auto_shuffle': 'Automatisch mischen',
      'automatically_shuffle': 'Automatisch mischen bei Wiedergabe',
      'gapless_playback': 'Nahtlose Wiedergabe',
      'seamless_transition': 'Nahtloser Übergang zwischen Titeln',
      'crossfade': 'Überblendung',
      'seconds_crossfade': 's Überblendung',
      'off': 'Aus',
      'apply': 'Anwenden',
      'about': 'Über',
      'version': 'Version',
      'built_with_flutter': 'Mit Flutter & Liebe entwickelt',
      'credits': 'Danksagungen',
      'open_source_licenses': 'Open-Source-Komponenten und Lizenzen',
      'developer': 'Entwickler',
      'repeat_all': 'Alle wiederholen',
      'repeat_one': 'Einzeln wiederholen',
      'shuffled': 'Zufallswiedergabe',
      'added_to': 'Hinzugefügt zu',
      'created_and_added_to': 'Erstellt und hinzugefügt zu',
      'no_songs': 'Keine Titel',
      'english': 'Englisch',
      'turkish': 'Türkisch',
      'german': 'Deutsch',
      'scan_media_library': 'Mediathek scannen',
      'import_from_apple_music': 'Aus Apple Music Mediathek importieren',
      'browse_files': 'Dateien durchsuchen',
      'select_audio_files': 'Audiodateien aus der Dateien-App auswählen',
      'import_from_folder_title': 'Aus Ordner importieren',
      'scan_specific_folder': 'Bestimmten Ordner scannen',
      'seconds': 'Sekunden',
      'melodi': 'Melodi',
      'add_to_queue': 'Zur Warteschlange hinzufügen',
      'play_next': 'Als Nächstes abspielen',
      'view_album': 'Album anzeigen',
      'view_artist': 'Künstler anzeigen',
      'watched_folder': 'Überwachter Ordner',
      'auto_scan_folder': 'Ordner bei jedem Start automatisch scannen',
      'watching': 'Überwacht',
      'folder_set': 'Ordner festgelegt',
      'could_not_open_link': 'Link konnte nicht geöffnet werden',
      'youtube_search_hint': 'Auf YouTube suchen',
      'downloading': 'Herunterladen...',
      'download_complete': 'Download abgeschlossen',
      'download_failed': 'Download fehlgeschlagen',
      'loading_song': 'Laden',
      'sleep_timer_canceled': 'Schlaftimer abgebrochen',
      'output_selection': 'Auswahl der Audioausgabe',
      'device_selection': 'Geräteauswahl',
      'artist_label': 'Künstler',
      'album_label': 'Album',
      'genre_label': 'Genre',
      'year_label': 'Jahr',
      'track_label': 'Titel',
      'bitrate_label': 'Bitrate',
      'duration_label': 'Dauer',
      'file_label': 'Datei',
      'accent_color': 'Akzentfarbe',
      'tap_to_change': 'Zum Ändern tippen',
      'background': 'Hintergrund',
      'surface': 'Oberfläche',
      'card': 'Karte',
      'text_primary': 'Primärtext',
      'text_secondary': 'Sekundärtext',
      'reset_colors': 'Farben zurücksetzen',
      'default_color': 'Standard',
      'create_playlist': 'Playlist erstellen',
      'share_song': 'Song teilen',
      'share_file': 'Audiodatei teilen',
      'now_playing_queue': 'Wiedergabe aus Warteschlange',
      'song_count': 'Titel',
      'min': 'Min',
      'hr': 'Std',
      'dynamic_colors': 'Dynamische Farben',
      'apply_album_colors': 'Farben vom Albumcover übernehmen',
      'youtube_music': 'YouTube Music',
      'connect_ytmusic_description': 'Importiere deine YouTube Music Bibliothek. Verbinde mit deinem Browser-Cookie.',
      'ytmusic_cookie_instructions': '1. Gehe zu music.youtube.com im Browser\n2. Melde dich an\n3. Öffne DevTools (F12) > Application > Cookies\n4. Kopiere den Wert von "__Secure-3PSAPISID"\n5. Füge ihn unten ein',
      'paste_ytmusic_cookie': 'SAPISID-Cookie einfügen',
      'import_songs': 'Titel importieren',
      'import_albums': 'Alben importieren',
      'connect_youtube_music': 'YouTube Music verbinden',
      'auto_sync': 'Auto-Sync',
      'sync_time': 'Sync-Zeit',
      'wifi_only': 'Nur WLAN',
      'sync_schedule': 'Sync-Plan',
      'online_mode': 'Online-Modus',
      'offline_mode': 'Offline-Modus',
      'stream_on_cellular': 'Streaming über Mobilfunk',
      'streaming': 'Streaming',
      'synced_lyrics': 'Synchronisierte Liedtexte',
      'no_lyrics': 'Keine Liedtexte verfügbar',
      'instrumental': 'Instrumental',
    },
  };

  static String tr(String key) {
    final map = _strings[currentLocale] ?? _strings['en']!;
    return map[key] ?? _strings['en']![key] ?? key;
  }
}

extension AppLocaleExtension on BuildContext {
  String tr(String key) => AppLocale.tr(key);
}
